import React, { createContext, useContext, useState, useEffect } from 'react';

export const INDIAN_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' }
];

export const TRANSLATIONS = {
  en: {
    appTitle: 'AapdaNetra Crisis Decision Support',
    appSubtitle: 'Real-Time Geospatial Intelligence • ML Predictions • Emergency Guidance',
    home: 'Home',
    about: 'About',
    howItWorks: 'How It Works',
    contact: 'Contact',
    changeLocation: 'Change Location',
    useGps: 'Use My Live GPS Location',
    gpsActive: 'GPS Active',
    searchDistrict: 'Search district (e.g. Bhopal, Pune)...',
    locationTelemetry: 'LOCATION TELEMETRY',
    notifications: 'Notifications',
    signOut: 'Sign out',
    citizen: 'Citizen',
    admin: 'Admin',
    welcomeBack: 'Welcome Back',
    signInPrompt: 'Sign in to continue to AapdaNetra',
    adminAccess: 'Secure Administrator Access',
    mobileNumber: 'Mobile Number',
    enterMobile: 'Enter 10-digit mobile number',
    mobileHelper: 'Registered 10-digit Indian mobile number.',
    emailAddress: 'Email Address',
    citizenEmail: 'Citizen Email Address',
    adminId: 'Admin ID (12 characters)',
    password: 'Password',
    enterPassword: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signInWithMobile: 'Sign In with Mobile Number',
    signInWithEmail: 'Sign In with Email',
    signInAsAdmin: 'Sign In as Administrator',
    or: 'OR',
    signInGoogle: 'Sign in with Google',
    dontHaveAccount: "Don't have an account?",
    createAccount: 'Create an account',
    saferPeople: 'SAFER PEOPLE | STRONGER COMMUNITIES',
    platformSubtitle: 'Public Safety & Emergency Decision Support Platform',
    missionStatement: 'Intelligent disaster risk management for a safer, more resilient India.',
    anticipateRisks: 'Anticipate Risks',
    anticipateHelper: 'Data-driven insights',
    enableResponse: 'Enable Faster Response',
    responseHelper: 'Coordinated action',
    buildCommunities: 'Build Safer Communities',
    communitiesHelper: 'A more resilient tomorrow',
    togetherSafer: 'Together for a Safer Tomorrow',
    selectLanguage: 'Select Language'
  },
  hi: {
    appTitle: 'आपदानेत्र संकट निर्णय सहायता',
    appSubtitle: 'वास्तविक समय भू-स्थानिक बुद्धिमत्ता • मशीन लर्निंग पूर्वानुमान • आपातकालीन मार्गदर्शन',
    home: 'मुख्य पृष्ठ',
    about: 'हमारे बारे में',
    howItWorks: 'कार्यप्रणाली',
    contact: 'संपर्क करें',
    changeLocation: 'स्थान बदलें',
    useGps: 'लाइव जीपीएस स्थान का उपयोग करें',
    gpsActive: 'जीपीएस सक्रिय',
    searchDistrict: 'जिला खोजें (उदा. भोपाल, पुणे)...',
    locationTelemetry: 'स्थान टेलीमेट्री',
    notifications: 'सूचनाएं',
    signOut: 'लॉग आउट',
    citizen: 'नागरिक',
    admin: 'व्यवस्थापक',
    welcomeBack: 'वापसी पर स्वागत है',
    signInPrompt: 'आपदानेत्र में जारी रखने के लिए साइन इन करें',
    adminAccess: 'सुरक्षित व्यवस्थापक पहुंच',
    mobileNumber: 'मोबाइल नंबर',
    enterMobile: '10 अंकों का मोबाइल नंबर दर्ज करें',
    mobileHelper: 'पंजीकृत 10-अंकीय भारतीय मोबाइल नंबर।',
    emailAddress: 'ईमेल पता',
    citizenEmail: 'नागरिक ईमेल पता',
    adminId: 'व्यवस्थापक आईडी (12 वर्ण)',
    password: 'पासवर्ड',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    signInWithMobile: 'मोबाइल नंबर से साइन इन करें',
    signInWithEmail: 'ईमेल से साइन इन करें',
    signInAsAdmin: 'व्यवस्थापक के रूप में साइन इन करें',
    or: 'अथवा',
    signInGoogle: 'Google के साथ साइन इन करें',
    dontHaveAccount: 'खाता नहीं है?',
    createAccount: 'खाता बनाएं',
    saferPeople: 'सुरक्षित नागरिक | सुदृढ़ समुदाय',
    platformSubtitle: 'लोक सुरक्षा एवं आपातकालीन निर्णय समर्थन मंच',
    missionStatement: 'सुरक्षित, अधिक सशक्त भारत के लिए बुद्धिमत्तापूर्ण आपदा जोखिम प्रबंधन।',
    anticipateRisks: 'जोखिमों का पूर्वानुमान',
    anticipateHelper: 'डेटा-संचालित अंतर्दृष्टि',
    enableResponse: 'त्वरित प्रतिक्रिया',
    responseHelper: 'समन्वित कार्यवाही',
    buildCommunities: 'सुरक्षित समुदाय निर्माण',
    communitiesHelper: 'एक अधिक सशक्त कल',
    togetherSafer: 'सुरक्षित कल के लिए एकजुट',
    selectLanguage: 'भाषा चुनें'
  },
  bn: {
    appTitle: 'আপদানেত্র সংকট সিদ্ধান্ত সহায়তা',
    appSubtitle: 'রিয়েল-টাইম ভূ-স্থানীয় বুদ্ধিমত্তা • এআই পূর্বাভাস • জরুরি সহায়তা',
    home: 'হোম',
    about: 'আমাদের সম্পর্কে',
    howItWorks: 'পদ্ধতি',
    contact: 'যোগাযোগ',
    changeLocation: 'অবস্থান পরিবর্তন',
    useGps: 'লাইভ জিপিএস অবস্থান ব্যবহার করুন',
    gpsActive: 'জিপিএস সক্রিয়',
    searchDistrict: 'জেলা খুঁজুন (যেমন কলকাতা, বাঁকুড়া)...',
    locationTelemetry: 'অবস্থান টেলিমেট্রি',
    notifications: 'বিজ্ঞপ্তি',
    signOut: 'লগআউট',
    citizen: 'নাগরিক',
    admin: 'প্রশাসক',
    welcomeBack: 'স্বাগতম',
    signInPrompt: 'আপদানেত্রতে চালিয়ে যেতে সাইন ইন করুন',
    adminAccess: 'নিরাপদ প্রশাসক অ্যাক্সেস',
    mobileNumber: 'মোবাইল নম্বর',
    enterMobile: '১০ সংখ্যার মোবাইল নম্বর লিখুন',
    mobileHelper: 'নিবন্ধিত ভারতীয় মোবাইল নম্বর।',
    emailAddress: 'ইমেইল ঠিকানা',
    citizenEmail: 'নাগরিক ইমেইল ঠিকানা',
    adminId: 'অ্যাডমিন আইডি',
    password: 'পাসওয়ার্ড',
    enterPassword: 'পাসওয়ার্ড লিখুন',
    rememberMe: 'আমাকে মনে রাখুন',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    signInWithMobile: 'মোবাইল দিয়ে সাইন ইন করুন',
    signInWithEmail: 'ইমেইল দিয়ে সাইন ইন করুন',
    signInAsAdmin: 'প্রশাসক হিসাবে সাইন ইন করুন',
    or: 'অথবা',
    signInGoogle: 'গুগল দিয়ে সাইন ইন করুন',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    saferPeople: 'নিরাপদ মানুষ | শক্তিশালী সমাজ',
    platformSubtitle: 'জননিরাপত্তা ও জরুরি সিদ্ধান্ত সহায়তা প্ল্যাটফর্ম',
    missionStatement: 'একটি নিরাপদ ও স্থিতিশীল ভারতের জন্য দুর্যোগ ঝুঁকি ব্যবস্থাপনা।',
    anticipateRisks: 'ঝুঁকি পূর্বাভাস',
    anticipateHelper: 'উপাত্তভিত্তিক তথ্য',
    enableResponse: 'দ্রুত সাড়া প্রদান',
    responseHelper: 'সমন্বিত পদক্ষেপ',
    buildCommunities: 'নিরাপদ সমাজ গঠন',
    communitiesHelper: 'একটি উজ্জ্বল ভবিষ্যৎ',
    togetherSafer: 'নিরাপদ আগামীর জন্য একসাথে',
    selectLanguage: 'ভাষা নির্বাচন করুন'
  },
  te: {
    appTitle: 'ఆపదనేత్ర విపత్తు నిర్ణయ మద్దతు',
    appSubtitle: 'నిజ-సమయ జియోస్పేషియల్ సమాచారం • ఏఐ అంచనాలు • అత్యవసర మార్గదర్శనం',
    home: 'హోమ్',
    about: 'మా గురించి',
    howItWorks: 'ఎలా పనిచేస్తుంది',
    contact: 'సంప్రదించండి',
    changeLocation: 'స్థానాన్ని మార్చండి',
    useGps: 'నా లైవ్ జీపీఎస్ ఉపయోగించండి',
    gpsActive: 'జీపీఎస్ సక్రియం',
    searchDistrict: 'జిల్లాను వెతకండి (ఉదా. విశాఖపట్నం, విజయవాడ)...',
    locationTelemetry: 'లొకేషన్ టెలిమెట్రీ',
    notifications: 'నోటిఫికేషన్లు',
    signOut: 'లాగ్ అవుట్',
    citizen: 'పౌరుడు',
    admin: 'నిర్వాహకుడు',
    welcomeBack: 'స్వాగతం',
    signInPrompt: 'ఆపదనేత్రకు కొనసాగడానికి సైన్ ఇన్ చేయండి',
    adminAccess: 'సురక్షిత అడ్మిన్ యాక్సెస్',
    mobileNumber: 'మొబైల్ సంఖ్య',
    enterMobile: '10 అంకెల మొబైల్ సంఖ్య నమోదు చేయండి',
    mobileHelper: 'రిజిస్టర్డ్ భారతీయ మొబైల్ సంఖ్య.',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    citizenEmail: 'పౌర ఈమెయిల్ చిరునామా',
    adminId: 'అడ్మిన్ ఐడీ',
    password: 'పాస్‌వర్డ్',
    enterPassword: 'పాస్‌వర్డ్ నమోదు చేయండి',
    rememberMe: 'నన్ను గుర్తుంచుకో',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    signInWithMobile: 'మొబైల్ తో సైన్ ఇన్ చేయండి',
    signInWithEmail: 'ఈమెయిల్ తో సైన్ ఇన్ చేయండి',
    signInAsAdmin: 'అడ్మిన్ గా సైన్ ఇన్ చేయండి',
    or: 'లేదా',
    signInGoogle: 'గూగుల్ తో సైన్ ఇన్ చేయండి',
    dontHaveAccount: 'ఖాతా లేదా?',
    createAccount: 'ఖాతా సృష్టించండి',
    saferPeople: 'సురక్షిత ప్రజలు | దృఢమైన సమాజం',
    platformSubtitle: 'ప్రజా భద్రత & అత్యవసర నిర్ణయ మద్దతు వేదిక',
    missionStatement: 'మరింత సురక్షితమైన భారతదేశం కోసం తెలివైన విపత్తు నిర్వహణ.',
    anticipateRisks: 'ప్రమాదాలను ముందే ఊహించండి',
    anticipateHelper: 'డేటా ఆధారిత విశ్లేషణ',
    enableResponse: 'వేగవంతమైన స్పందన',
    responseHelper: 'సమన్వయ చర్యలు',
    buildCommunities: 'సురక్షిత సమాజాల నిర్మాణం',
    communitiesHelper: 'మంచి భవిష్యత్తు కోసం',
    togetherSafer: 'సురక్షిత రేపటి కోసం కలిసికట్టుగా',
    selectLanguage: 'భాషను ఎంచుకోండి'
  },
  mr: {
    appTitle: 'आपदानेत्र आपत्कालीन निर्णय सहाय्य',
    appSubtitle: 'रिअल-टाइम भौगोलिक बुद्धिमत्ता • एआय अंदाज • आणीबाणी मार्गदर्शन',
    home: 'मुख्यपृष्ठ',
    about: 'आमच्याबद्दल',
    howItWorks: 'कसे कार्य करते',
    contact: 'संपर्क',
    changeLocation: 'स्थान बदला',
    useGps: 'माझे थेट जीपीएस स्थान वापरा',
    gpsActive: 'जीपीएस सक्रिय',
    searchDistrict: 'जिल्हा शोधा (उदा. मुंबई, पुणे)...',
    locationTelemetry: 'स्थान टेलीमेट्री',
    notifications: 'सूचना',
    signOut: 'लॉग आऊट',
    citizen: 'नागरिक',
    admin: 'प्रशासक',
    welcomeBack: 'पुन्हा स्वागत आहे',
    signInPrompt: 'आपदानेत्र सुरू ठेवण्यासाठी साइन इन करा',
    adminAccess: 'सुरक्षित प्रशासक प्रवेश',
    mobileNumber: 'मोबाईल क्रमांक',
    enterMobile: '१० अंकी मोबाईल क्रमांक टाका',
    mobileHelper: 'नोंदणीकृत १० अंकी भारतीय मोबाईल क्रमांक.',
    emailAddress: 'ईमेल पत्ता',
    citizenEmail: 'नागरिक ईमेल पत्ता',
    adminId: 'अॅडमिन आयडी',
    password: 'पासवर्ड',
    enterPassword: 'पासवर्ड टाका',
    rememberMe: 'मला लक्षात ठेवा',
    forgotPassword: 'पासवर्ड विसरलात?',
    signInWithMobile: 'मोबाईलने साइन इन करा',
    signInWithEmail: 'ईमेलने साइन इन करा',
    signInAsAdmin: 'प्रशासक म्हणून साइन इन करा',
    or: 'किंवा',
    signInGoogle: 'Google सह साइन इन करा',
    dontHaveAccount: 'खाते नाही?',
    createAccount: 'खाते तयार करा',
    saferPeople: 'सुरक्षित नागरिक | सक्षम समाज',
    platformSubtitle: 'सार्वजनिक सुरक्षा आणि आपत्कालीन निर्णय समर्थन मंच',
    missionStatement: 'सुरक्षित आणि सक्षम भारतासाठी प्रगत आपत्ती जोखीम व्यवस्थापन.',
    anticipateRisks: 'जोखमींचा अंदाज घ्या',
    anticipateHelper: 'डेटा-चालित माहिती',
    enableResponse: 'जलद प्रतिसाद द्या',
    responseHelper: 'समन्वित कृती',
    buildCommunities: 'सुरक्षित समुदाय बनवा',
    communitiesHelper: 'उद्याच्या सुरक्षित भविष्यासाठी',
    togetherSafer: 'सुरक्षित भविष्यासाठी एकत्र',
    selectLanguage: 'भाषा निवडा'
  },
  ta: {
    appTitle: 'ஆபதாநேத்ரா அவசரகால முடிவு ஆதரவு',
    appSubtitle: 'நேரலை புவிசார் நுண்ணறிவு • ஏஐ முன்னறிவிப்பு • அவசர வழிகாட்டுதல்',
    home: 'முகப்பு',
    about: 'எங்களை பற்றி',
    howItWorks: 'செயல்முறை',
    contact: 'தொடர்பு',
    changeLocation: 'இருப்பிடம் மாற்றுக',
    useGps: 'என் ஜிபிஎஸ் இருப்பிடத்தைப் பயன்படுத்து',
    gpsActive: 'ஜிபிஎஸ் செயலில்',
    searchDistrict: 'மாவட்டத்தைத் தேடுக (எ.கா. சென்னை, மதுரை)...',
    locationTelemetry: 'இருப்பிட தொலைஅளவியல்',
    notifications: 'அறிவிப்புகள்',
    signOut: 'வெளியேறு',
    citizen: 'குடிமகன்',
    admin: 'நிர்வாகி',
    welcomeBack: 'நல்வரவு',
    signInPrompt: 'தொடர உள்நுழைக',
    adminAccess: 'பாதுகாப்பான நிர்வாக அணுகல்',
    mobileNumber: 'கைபேசி எண்',
    enterMobile: '10 இலக்க கைபேசி எண் உள்ளிடுக',
    mobileHelper: 'பதிவுசெய்யப்பட்ட கைபேசி எண்.',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    citizenEmail: 'குடிமகன் மின்னஞ்சல்',
    adminId: 'நிர்வாகி ஐடி',
    password: 'கடவுச்சொல்',
    enterPassword: 'கடவுச்சொல் உள்ளிடுக',
    rememberMe: 'என்னை நினைவில் கொள்க',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    signInWithMobile: 'கைபேசி மூலம் உள்நுழைக',
    signInWithEmail: 'மின்னஞ்சல் மூலம் உள்நுழைக',
    signInAsAdmin: 'நிர்வாகியாக உள்நுழைக',
    or: 'அல்லது',
    signInGoogle: 'Google மூலம் உள்நுழைக',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    createAccount: 'கணக்கு உருவாக்குக',
    saferPeople: 'பாதுகாப்பான மக்கள் | வலிமையான சமூகம்',
    platformSubtitle: 'பொது பாதுகாப்பு & அவசரகால முடிவு ஆதரவு தளம்',
    missionStatement: 'பாதுகாப்பான இந்தியாவிற்கான பேரிடர் இடர் மேலாண்மை.',
    anticipateRisks: 'ஆபத்துகளை கணிக்கவும்',
    anticipateHelper: 'தரவு அடிப்படையிலான நுண்ணறிவு',
    enableResponse: 'விரைவான நடவடிக்கை',
    responseHelper: 'ஒருங்கிணைந்த செயல்பாடு',
    buildCommunities: 'பாதுகாப்பான சமுதாயம்',
    communitiesHelper: 'சிறந்த நாளைய விடியலுக்காக',
    togetherSafer: 'பாதுகாப்பான நாளைக்காக ஒன்றிணைவோம்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்'
  },
  gu: {
    appTitle: 'આપદાનેત્ર આપત્તિ નિર્ણય સહાય',
    appSubtitle: 'રીઅલ-ટાઇમ ભૌગોલિક ઇન્ટેલિજન્સ • એઆઈ આગાહી • કટોકટી માર્ગદર્શન',
    home: 'હોમ',
    about: 'અમારા વિશે',
    howItWorks: 'કેવી રીતે કાર્ય કરે છે',
    contact: 'સંપર્ક',
    changeLocation: 'સ્થાન બદલો',
    useGps: 'મારું જીપીએસ વાપરો',
    gpsActive: 'જીપીએસ સક્રિય',
    searchDistrict: 'જિલ્લો શોધો (દા.ત. અમદાવાદ, સુરત)...',
    locationTelemetry: 'સ્થાન ટેલિમેટ્રી',
    notifications: 'સૂચનાઓ',
    signOut: 'લૉગ આઉટ',
    citizen: 'નાગરિક',
    admin: 'વહીવટકર્તા',
    welcomeBack: 'સ્વાગત છે',
    signInPrompt: 'ચાલુ રાખવા માટે સાઇન ઇન કરો',
    adminAccess: 'સુરક્ષિત એડમિન ઍક્સેસ',
    mobileNumber: 'મોબાઇલ નંબર',
    enterMobile: '૧૦ અંકનો મોબાઇલ નંબર દાખલ કરો',
    mobileHelper: 'નોંધાયેલ ૧૦ અંકનો ભારતીય મોબાઇલ નંબર.',
    emailAddress: 'ઈમેલ સરનામું',
    citizenEmail: 'નાગરિક ઈમેલ સરનામું',
    adminId: 'એડમિન આઈડી',
    password: 'પાસવર્ડ',
    enterPassword: 'પાસવર્ડ દાખલ કરો',
    rememberMe: 'મને યાદ રાખો',
    forgotPassword: 'પાસવર્ડ ભૂલી ગયા?',
    signInWithMobile: 'મોબાઇલથી સાઇન ઇન કરો',
    signInWithEmail: 'ઈમેલથી સાઇન ઇન કરો',
    signInAsAdmin: 'એડમિન તરીકે સાઇન ઇન કરો',
    or: 'અથવા',
    signInGoogle: 'Google સાથે સાઇન ઇન કરો',
    dontHaveAccount: 'ખાતું નથી?',
    createAccount: 'ખાતું બનાવો',
    saferPeople: 'સુરક્ષિત લોકો | મજબૂત સમુદાય',
    platformSubtitle: 'જાહેર સલામતી અને કટોકટી નિર્ણય સહાય પ્લેટફોર્મ',
    missionStatement: 'સુરક્ષિત ભારત માટે આપત્તિ જોખમ વ્યવસ્થાપન.',
    anticipateRisks: 'જોખમોની આગાહી કરો',
    anticipateHelper: 'ડેટા-સંચાલિત માહિતી',
    enableResponse: 'ઝડપી પ્રતિસાદ',
    responseHelper: 'સંકલિત પગલાં',
    buildCommunities: 'સુરક્ષિત સમુદાય બનાવો',
    communitiesHelper: 'વધુ સુરક્ષિત આવતીકાલ માટે',
    togetherSafer: 'સુરક્ષિત આવતીકાલ માટે સાથે',
    selectLanguage: 'ભાષા પસંદ કરો'
  },
  kn: {
    appTitle: 'ಆಪದನೇತ್ರ ವಿಪತ್ತು ನಿರ್ಧಾರ ಬೆಂಬಲ',
    appSubtitle: 'ನೈಜ-ಸಮಯದ ಭೌಗೋಳಿಕ ಮಾಹಿತಿ • ಎಐ ಮುನ್ಸೂಚನೆ • ತುರ್ತು ಮಾರ್ಗದರ್ಶನ',
    home: 'ಮುಖಪುಟ',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    howItWorks: 'ಕಾರ್ಯವಿಧಾನ',
    contact: 'ಸಂಪರ್ಕ',
    changeLocation: 'ಸ್ಥಳ ಬದಲಾಯಿಸಿ',
    useGps: 'ನನ್ನ ಲೈವ್ ಜಿಪಿಎಸ್ ಬಳಸಿ',
    gpsActive: 'ಜಿಪಿಎಸ್ ಸಕ್ರಿಯ',
    searchDistrict: 'ಜಿಲ್ಲೆಯನ್ನು ಹುಡುಕಿ (ಉದಾ. ಬೆಂಗಳೂರು, ಮೈಸೂರು)...',
    locationTelemetry: 'ಸ್ಥಳ ಟೆಲಿಮೆಟ್ರಿ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    signOut: 'ಸೈನ್ ಔಟ್',
    citizen: 'ನಾಗರಿಕ',
    admin: 'ನಿರ್ವಾಹಕ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    signInPrompt: 'ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    adminAccess: 'ಸುರಕ್ಷಿತ ಅಡ್ಮಿನ್ ಪ್ರವೇಶ',
    mobileNumber: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    enterMobile: '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    mobileHelper: 'ನೋಂದಾಯಿತ ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ.',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    citizenEmail: 'ನಾಗರಿಕ ಇಮೇಲ್ ವಿಳಾಸ',
    adminId: 'ಅಡ್ಮಿನ್ ಐಡಿ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    enterPassword: 'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    rememberMe: 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    signInWithMobile: 'ಮೊಬೈಲ್ ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    signInWithEmail: 'ಇಮೇಲ್ ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    signInAsAdmin: 'ಅಡ್ಮಿನ್ ಆಗಿ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    or: 'ಅಥವಾ',
    signInGoogle: 'ಗೂಗಲ್ ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    dontHaveAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    createAccount: 'ಖಾತೆ ತೆರೆಯಿರಿ',
    saferPeople: 'ಸುರಕ್ಷಿತ ಜನರು | ಬಲಿಷ್ಠ ಸಮುದಾಯ',
    platformSubtitle: 'ಸಾರ್ವಜನಿಕ ಸುರಕ್ಷತೆ ಮತ್ತು ತುರ್ತು ನಿರ್ಧಾರ ಬೆಂಬಲ ವೇದಿಕೆ',
    missionStatement: 'ಸುರಕ್ಷಿತ ಭಾರತಕ್ಕಾಗಿ ಬುದ್ಧಿವಂತ ವಿಪತ್ತು ನಿರ್ವಹಣೆ.',
    anticipateRisks: 'ಅಪಾಯಗಳನ್ನು ಊಹಿಸಿ',
    anticipateHelper: 'ಡೇಟಾ ಆಧಾರಿತ ಮಾಹಿತಿ',
    enableResponse: 'ತ್ವರಿತ ಪ್ರತಿಕ್ರಿಯೆ',
    responseHelper: 'ಸಂಘಟಿತ ಕ್ರಮ',
    buildCommunities: 'ಸುರಕ್ಷಿತ ಸಮುದಾಯಗಳ ನಿರ್ಮಾಣ',
    communitiesHelper: 'ಉತ್ತಮ ನಾಳೆಗಾಗಿ',
    togetherSafer: 'ಸುರಕ್ಷಿತ ನಾಳೆಗಾಗಿ ಒಟ್ಟಾಗಿ',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ'
  },
  ml: {
    appTitle: 'ആപദനേത്ര ദുരന്ത നിവാരണ പിന്തുണ',
    appSubtitle: 'തത്സമയ ഭൗമ വിവരങ്ങൾ • എഐ പ്രവചനങ്ങൾ • അടിയന്തര മാർഗ്ഗനിർദ്ദേശം',
    home: 'ഹോം',
    about: 'ഞങ്ങളെക്കുറിച്ച്',
    howItWorks: 'പ്രവർത്തനരീതി',
    contact: 'ബന്ധപ്പെടുക',
    changeLocation: 'സ്ഥലം മാറ്റുക',
    useGps: 'എന്റെ ലൈവ് ജിപിഎസ് ഉപയോഗിക്കുക',
    gpsActive: 'ജിപിഎസ് സജീവം',
    searchDistrict: 'ജില്ല തിരയുക (ഉദാ. കൊച്ചി, കോഴിക്കോട്)...',
    locationTelemetry: 'ലൊക്കേഷൻ ടെലിമെട്രി',
    notifications: 'അറിയിപ്പുകൾ',
    signOut: 'ലോഗ് ഔട്ട്',
    citizen: 'പൗരൻ',
    admin: 'അഡ്മിൻ',
    welcomeBack: 'സ്വാഗതം',
    signInPrompt: 'തുടരാൻ സൈൻ ഇൻ ചെയ്യുക',
    adminAccess: 'സുരക്ഷിത അഡ്മിൻ ആക്സസ്',
    mobileNumber: 'മൊബൈൽ നമ്പർ',
    enterMobile: '10 അക്ക മൊബൈൽ നമ്പർ നൽകുക',
    mobileHelper: 'രജിസ്റ്റർ ചെയ്ത മൊബൈൽ നമ്പർ.',
    emailAddress: 'ഇമെയിൽ വിലാസം',
    citizenEmail: 'പൗരന്റെ ഇമെയിൽ',
    adminId: 'അഡ്മിൻ ഐഡി',
    password: 'പാസ്‌വേഡ്',
    enterPassword: 'പാസ്‌വേഡ് നൽകുക',
    rememberMe: 'എന്നെ ഓർക്കുക',
    forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
    signInWithMobile: 'മൊബൈൽ ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക',
    signInWithEmail: 'ഇമെയിൽ ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക',
    signInAsAdmin: 'അഡ്മിനായി സൈൻ ഇൻ ചെയ്യുക',
    or: 'അഥവാ',
    signInGoogle: 'Google വഴി സൈൻ ഇൻ ചെയ്യുക',
    dontHaveAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    createAccount: 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    saferPeople: 'സുരക്ഷിത ജനങ്ങൾ | കരുത്തുറ്റ സമൂഹം',
    platformSubtitle: 'പൊതു സുരക്ഷയും അടിയന്തര തീരുമാന സഹായ പ്ലാറ്റ്‌ഫോമും',
    missionStatement: 'സുരക്ഷിതമായ ഇന്ത്യക്കായി മികച്ച ദുരന്ത നിവാരണം.',
    anticipateRisks: 'അപകടങ്ങൾ മുൻകൂട്ടി അറിയുക',
    anticipateHelper: 'ഡാറ്റാധിഷ്ഠിത വിവരങ്ങൾ',
    enableResponse: 'വേഗത്തിലുള്ള പ്രതികരണം',
    responseHelper: 'ഏകോപിത പ്രവർത്തനം',
    buildCommunities: 'സുരക്ഷിത സമൂഹം പണിയുക',
    communitiesHelper: 'സുരക്ഷിതമായ നാളേക്ക്',
    togetherSafer: 'സുരക്ഷിതമായ നാളേക്ക് ഒന്നിച്ച്',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക'
  },
  pa: {
    appTitle: 'ਆਪਦਾਨੇਤਰ ਆਫ਼ਤ ਫੈਸਲਾ ਸਹਾਇਤਾ',
    appSubtitle: 'ਰੀਅਲ-ਟਾਈਮ ਭੂਗੋਲਿਕ ਇੰਟੈਲੀਜੈਂਸ • ਏਆਈ ਭਵਿੱਖਬਾਣੀ • ਸੰਕਟਕਾਲੀਨ ਮਾਰਗਦਰਸ਼ਨ',
    home: 'ਹੋਮ',
    about: 'ਸਾਡੇ ਬਾਰੇ',
    howItWorks: 'ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    contact: 'ਸੰਪਰਕ',
    changeLocation: 'ਸਥਾਨ ਬਦਲੋ',
    useGps: 'ਮੇਰਾ ਲਾਈਵ ਜੀਪੀਐਸ ਵਰਤੋ',
    gpsActive: 'ਜੀਪੀਐਸ ਕਿਰਿਆਸ਼ੀਲ',
    searchDistrict: 'ਜ਼ਿਲ੍ਹਾ ਖੋਜੋ (ਜਿਵੇਂ ਚੰਡੀਗੜ੍ਹ, ਅੰਮ੍ਰਿਤਸਰ)...',
    locationTelemetry: 'ਸਥਾਨ ਟੈਲੀਮੈਟਰੀ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    signOut: 'ਲੌਗ ਆਉਟ',
    citizen: 'ਨਾਗਰਿਕ',
    admin: 'ਪ੍ਰਸ਼ਾਸਕ',
    welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    signInPrompt: 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
    adminAccess: 'ਸੁਰੱਖਿਅਤ ਪ੍ਰਸ਼ਾਸਕ ਪਹੁੰਚ',
    mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    enterMobile: '10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    mobileHelper: 'ਰਜਿਸਟਰਡ ਭਾਰਤੀ ਮੋਬਾਈਲ ਨੰਬਰ।',
    emailAddress: 'ਈਮੇਲ ਪਤਾ',
    citizenEmail: 'ਨਾਗਰਿਕ ਈਮੇਲ ਪਤਾ',
    adminId: 'ਐਡਮਿਨ ਆਈਡੀ',
    password: 'ਪਾਸਵਰਡ',
    enterPassword: 'ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
    rememberMe: 'ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ',
    forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    signInWithMobile: 'ਮੋਬਾਈਲ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    signInWithEmail: 'ਈਮੇਲ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    signInAsAdmin: 'ਪ੍ਰਸ਼ਾਸਕ ਵਜੋਂ ਸਾਈਨ ਇਨ ਕਰੋ',
    or: 'ਜਾਂ',
    signInGoogle: 'Google ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    dontHaveAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    saferPeople: 'ਸੁਰੱਖਿਅਤ ਲੋਕ | ਮਜ਼ਬੂਤ ਸਮਾਜ',
    platformSubtitle: 'ਜਨਤਕ ਸੁਰੱਖਿਆ ਅਤੇ ਸੰਕਟਕਾਲੀਨ ਫੈਸਲਾ ਸਹਾਇਤਾ ਮੰਚ',
    missionStatement: 'ਸੁਰੱਖਿਅਤ ਭਾਰਤ ਲਈ ਆਫ਼ਤ ਜੋਖਮ ਪ੍ਰਬੰਧਨ।',
    anticipateRisks: 'ਜੋਖਮਾਂ ਦਾ ਅੰਦਾਜ਼ਾ ਲਗਾਓ',
    anticipateHelper: 'ਡਾਟਾ-ਅਧਾਰਤ ਜਾਣਕਾਰੀ',
    enableResponse: 'ਤੇਜ਼ ਕਾਰਵਾਈ',
    responseHelper: 'ਤਾਲਮੇਲ ਵਾਲੀ ਕਾਰਵਾਈ',
    buildCommunities: 'ਸੁਰੱਖਿਅਤ ਸਮਾਜ ਬਣਾਓ',
    communitiesHelper: 'ਸੁਰੱਖਿਅਤ ਭਵਿੱਖ ਲਈ',
    togetherSafer: 'ਸੁਰੱਖਿਅਤ ਭਵਿੱਖ ਲਈ ਇਕੱਠੇ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ'
  },
  or: {
    appTitle: 'ଆପଦାନେତ୍ର ବିପର୍ଯ୍ୟୟ ନିଷ୍ପତ୍ତି ସହାୟତା',
    appSubtitle: 'ରିଅଲ-ଟାଇମ୍ ଭୌଗୋଳିକ ସୂଚନା • ଏଆଇ ପୂର୍ବାନୁମାନ • ଜରୁରୀକାଳୀନ ମାର୍ଗଦର୍ଶନ',
    home: 'ମୂଳପୃଷ୍ଠା',
    about: 'ଆମ ବିଷୟରେ',
    howItWorks: 'କିପରି କାର୍ଯ୍ୟ କରେ',
    contact: 'ଯୋଗାଯୋଗ',
    changeLocation: 'ସ୍ଥାନ ପରିବର୍ତ୍ତନ',
    useGps: 'ମୋର ଲାଇଭ୍ ଜିପିଏସ୍ ବ୍ୟବହାର କରନ୍ତୁ',
    gpsActive: 'ଜିପିଏସ୍ ସକ୍ରିୟ',
    searchDistrict: 'ଜିଲ୍ଲା ଖୋଜନ୍ତୁ (ଯଥା ଭୁବନେଶ୍ୱର, କଟକ)...',
    locationTelemetry: 'ସ୍ଥାନ ଟେଲିମେଟ୍ରି',
    notifications: 'ବିଜ୍ଞପ୍ତି',
    signOut: 'ଲଗ୍ ଆଉଟ୍',
    citizen: 'ନାଗରିକ',
    admin: 'ପ୍ରଶାସକ',
    welcomeBack: 'ସ୍ୱାଗତ',
    signInPrompt: 'ଜାରି ରଖିବାକୁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    adminAccess: 'ସୁରକ୍ଷିତ ପ୍ରଶାସକ ପ୍ରବେଶ',
    mobileNumber: 'ମୋବାଇଲ୍ ନମ୍ବର',
    enterMobile: '୧୦ ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ',
    mobileHelper: 'ପଞ୍ଜୀକୃତ ଭାରତୀୟ ମୋବାଇଲ୍ ନମ୍ବର।',
    emailAddress: 'ଇମେଲ୍ ଠିକଣା',
    citizenEmail: 'ନାଗରିକ ଇମେଲ୍ ଠିକଣା',
    adminId: 'ଆଡମିନ୍ ଆଇଡି',
    password: 'ପାସୱାର୍ଡ',
    enterPassword: 'ପାସୱାର୍ଡ ଦିଅନ୍ତୁ',
    rememberMe: 'ମନେ ରଖନ୍ତୁ',
    forgotPassword: 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ?',
    signInWithMobile: 'ମୋବାଇଲ୍ ସହିତ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    signInWithEmail: 'ଇମେଲ୍ ସହିତ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    signInAsAdmin: 'ପ୍ରଶାସକ ଭାବରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    or: 'କିମ୍ବା',
    signInGoogle: 'Google ସହିତ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    dontHaveAccount: 'ଖାତା ନାହିଁ କି?',
    createAccount: 'ଖାତା ଖୋଲନ୍ତୁ',
    saferPeople: 'ସୁରକ୍ଷିତ ଲୋକ | ଶକ୍ତିଶାଳୀ ସମାଜ',
    platformSubtitle: 'ଜନସାଧାରଣ ସୁରକ୍ଷା ଓ ଜରୁରୀକାଳୀନ ନିଷ୍ପତ୍ତି ସହାୟତା ପ୍ଲାଟଫର୍ମ',
    missionStatement: 'ସୁରକ୍ଷିତ ଭାରତ ପାଇଁ ବିପର୍ଯ୍ୟୟ ବିପଦ ପରିଚାଳନା।',
    anticipateRisks: 'ବିପଦର ଆଗୁଆ ଅନୁମାନ',
    anticipateHelper: 'ତଥ୍ୟ-ଆଧାରିତ ସୂଚନା',
    enableResponse: 'ଦ୍ରୁତ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ',
    responseHelper: 'ସମନ୍ୱିତ ପଦକ୍ଷେପ',
    buildCommunities: 'ସୁରକ୍ଷିତ ସମାଜ ନିର୍ମାଣ',
    communitiesHelper: 'ଉନ୍ନତ ଭବିଷ୍ୟତ ପାଇଁ',
    togetherSafer: 'ସୁରକ୍ଷିତ ଆଗାମୀ କାଲି ପାଇଁ ଏକତ୍ର',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ'
  },
  as: {
    appTitle: 'আপদানেত্ৰ সংকট সিদ্ধান্ত সাহায্য',
    appSubtitle: 'ৰিয়েল-টাইম ভূ-স্থানিক বুদ্ধিমত্তা • এআই পূৰ্বাভাস • জৰুৰীকালীন নিৰ্দেশনা',
    home: 'গৃহ',
    about: 'আমাৰ বিষয়ে',
    howItWorks: 'কাৰ্যপদ্ধতি',
    contact: 'যোগাযোগ',
    changeLocation: 'স্থান সলনি কৰক',
    useGps: 'মোৰ লাইভ জিপিএছ ব্যৱহাৰ কৰক',
    gpsActive: 'জিপিএছ সক্ৰিয়',
    searchDistrict: 'জিলা সন্ধান কৰক (যেনে গুৱাহাটী, শিলচৰ)...',
    locationTelemetry: 'স্থান টেলিমেট্ৰি',
    notifications: 'জাননী',
    signOut: 'লগ আউট',
    citizen: 'নাগৰিক',
    admin: 'প্ৰশাসক',
    welcomeBack: 'স্বাগতম',
    signInPrompt: 'আগবাঢ়িবলৈ ছাইন ইন কৰক',
    adminAccess: 'সুৰক্ষিত প্ৰশাসক প্ৰৱেশ',
    mobileNumber: 'মোবাইল নম্বৰ',
    enterMobile: '১০ টা সংখ্যাৰ মোবাইল নম্বৰ দিয়ক',
    mobileHelper: 'পঞ্জীভুক্ত ভাৰতীয় মোবাইল নম্বৰ।',
    emailAddress: 'ইমেইল ঠিকনা',
    citizenEmail: 'নাগৰিক ইমেইল ঠিকনা',
    adminId: 'এডমিন আইডি',
    password: 'পাছৱৰ্ড',
    enterPassword: 'পাছৱৰ্ড দিয়ক',
    rememberMe: 'মনত ৰাখক',
    forgotPassword: 'পাছৱৰ্ড পাহৰিলে?',
    signInWithMobile: 'মোবাইলেৰে ছাইন ইন কৰক',
    signInWithEmail: 'ইমেইলেৰে ছাইন ইন কৰক',
    signInAsAdmin: 'প্ৰশাসক হিচাপে ছাইন ইন কৰক',
    or: 'অথবা',
    signInGoogle: 'Google ৰে ছাইন ইন কৰক',
    dontHaveAccount: 'একাউণ্ট নাই?',
    createAccount: 'একাউণ্ট সৃষ্টি কৰক',
    saferPeople: 'সুৰক্ষিত মানুহ | শক্তিশালী সমাজ',
    platformSubtitle: 'ৰাজহুৱা সুৰক্ষা আৰু জৰুৰীকালীন সিদ্ধান্ত সমৰ্থন মঞ্চ',
    missionStatement: 'সুৰক্ষিত আৰু শক্তিশালী ভাৰতৰ বাবে দুৰ্যোগ বিপদাশংকা ব্যৱস্থাপনা।',
    anticipateRisks: 'বিপদৰ আগলি বতৰা',
    anticipateHelper: 'তথ্য-আধাৰিত অন্তৰ্দৃষ্টি',
    enableResponse: 'দ্ৰুত সঁহাৰি',
    responseHelper: 'সমন্বিত পদক্ষেপ',
    buildCommunities: 'সুৰক্ষিত সমাজ গঠন',
    communitiesHelper: 'উজ্জ্বল ভৱিষ্যতৰ বাবে',
    togetherSafer: 'সুৰক্ষিত কাইলৈৰ বাবে একেলগে',
    selectLanguage: 'ভাষা বাছক'
  }
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key, fallback) => fallback || key,
  languages: INDIAN_LANGUAGES
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('aapdanetra_language') || 'en';
    } catch {
      return 'en';
    }
  });

  const setLanguage = (langCode) => {
    setLanguageState(langCode);
    try {
      localStorage.setItem('aapdanetra_language', langCode);
      document.documentElement.lang = langCode;
    } catch (e) {
      console.error(e);
    }
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key, fallback = '') => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict && langDict[key] !== undefined) {
      return langDict[key];
    }
    const defaultDict = TRANSLATIONS.en;
    if (defaultDict && defaultDict[key] !== undefined) {
      return defaultDict[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: INDIAN_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
