import React, { createContext, useContext, useState, useEffect } from 'react';

export const INDIAN_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' }
];

export const TRANSLATIONS = {
  en: {
    appTitle: 'AapdaNetra Crisis Decision Support',
    appSubtitle: 'Real-Time Geospatial Intelligence • ML Predictions • Emergency Guidance',
    home: 'Home',
    about: 'About',
    howItWorks: 'How It Works',
    contact: 'Contact',
    changeLocation: 'Change Location',
    useGps: 'Use My Live GPS Location',
    gpsActive: 'GPS Active',
    searchDistrict: 'Search district (e.g. Bhopal, Pune)...',
    locationTelemetry: 'LOCATION TELEMETRY',
    notifications: 'Notifications',
    signOut: 'Sign out',
    citizen: 'Citizen',
    admin: 'Admin',
    welcomeBack: 'Welcome Back',
    signInPrompt: 'Sign in to continue to AapdaNetra',
    adminAccess: 'Secure Administrator Access',
    mobileNumber: 'Mobile Number',
    enterMobile: 'Enter 10-digit mobile number',
    mobileHelper: 'Registered 10-digit Indian mobile number.',
    emailAddress: 'Email Address',
    citizenEmail: 'Citizen Email Address',
    citizenEmailHelper: 'Registered citizen email address.',
    adminId: 'Admin ID (12 characters)',
    adminIdHelper: "Format: Fixed 'NETRA' + 7 digits (e.g. NETRA0012121) or official admin email",
    password: 'Password',
    enterPassword: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    forgotAdminPassword: 'Forgot admin password?',
    signInWithMobile: 'Sign In with Mobile Number',
    signInWithEmail: 'Sign In with Email',
    signInAsAdmin: 'Sign In as Administrator',
    authenticating: 'Authenticating...',
    or: 'OR',
    signInGoogle: 'Sign in with Google',
    dontHaveAccount: "Don't have an account?",
    createAccount: 'Create an account',
    saferPeople: 'SAFER PEOPLE | STRONGER COMMUNITIES',
    platformSubtitle: 'Public Safety & Emergency Decision Support Platform',
    publicSafety: 'Public Safety & Emergency',
    decisionPlatform: 'Decision Support Platform',
    missionStatement: 'Intelligent disaster risk management for a safer, more resilient India.',
    anticipateRisks: 'Anticipate Risks',
    anticipateHelper: 'Data-driven insights',
    enableResponse: 'Enable Faster Response',
    responseHelper: 'Coordinated action',
    buildCommunities: 'Build Safer Communities',
    communitiesHelper: 'A more resilient tomorrow',
    together: 'Together',
    forASafer: 'for a Safer',
    tomorrow: 'Tomorrow',
    togetherSafer: 'Together for a Safer Tomorrow',
    disasterIntelligence: 'DISASTER INTELLIGENCE',
    selectLanguage: 'Select Language',
    footerResilient: 'Building a safer, more resilient tomorrow.',
    footerEmpowering: 'Empowering communities with data, intelligence, and timely action.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    allRightsReserved: '© 2026. All rights reserved.',

    // Sidebar
    aiDisasterIntelligence: 'AI Disaster Intelligence',
    cmdIntelligence: 'Command & Intelligence',
    commandDashboard: 'Command Dashboard',
    liveDisasterMap: 'Live Disaster Map',
    aiEmergencyAssistant: 'AI Emergency Assistant',
    analyticsPredictions: 'Analytics & Predictions',
    citizenReports: 'Citizen Reports',
    temporalForecasts: 'Temporal Forecasts',
    riskAnalysis: 'Risk Analysis (XAI)',
    whatIfSimulation: '"What If?" Simulation',
    operationsRelocation: 'Operations & Relocation',
    vulnerableHabitations: 'Vulnerable Habitations',
    shelterCapacity: 'Shelter Capacity',
    relocationPlans: 'Relocation Plans',
    userManagement: 'User Management',
    system: 'System',
    systemReports: 'System Reports',
    settings: 'Settings',

    // Dashboard
    crisisDecisionCockpit: 'Crisis Decision Cockpit',
    welcomeBackUser: 'Welcome back',
    monitoring: 'Monitoring',
    live: 'Live',
    liveMap: 'Live Map',
    quickActions: 'Quick Actions',
    citizenReportsCard: 'Citizen Reports',
    emergencyContacts: 'Emergency Contacts',
    shelterCapacityCard: 'Shelter Capacity',
    earlyWarnings: 'Early Warnings',
    simulationCard: 'What If? Simulation',
    currentSituation: 'Current Situation',
    activeAlerts: 'ACTIVE ALERTS',
    critical: 'Critical',
    sheltersReady: 'SHELTERS READY',
    operational: 'Operational',
    bedOccupancy: 'Bed Occupancy',
    operationalDesk: 'Operational Desk',
    populationAtRisk: 'POPULATION AT RISK',
    threatLevel: 'Threat',
    activeSectors: 'Active Sectors',
    riskDistribution: 'Risk Distribution',
    totalZones: 'Total Zones',
    lowRisk: 'Low Risk',
    mediumRisk: 'Medium Risk',
    highRisk: 'High Risk',
    viewFullRiskAnalysis: 'View full risk analysis',
    riskScoreTrend: '24-Hour Risk Score Trend',
    detailedTrendAnalysis: 'Detailed trend analysis',
    recentAlerts: 'Recent Alerts',
    viewAll: 'View All',
    aiAssistant: 'AI Assistant'
  },
  hi: {
    appTitle: 'आपदानेत्र संकट निर्णय सहायता',
    appSubtitle: 'वास्तविक समय भू-स्थानिक बुद्धिमत्ता • मशीन लर्निंग पूर्वानुमान • आपातकालीन मार्गदर्शन',
    home: 'मुख्य पृष्ठ',
    about: 'हमारे बारे में',
    howItWorks: 'कार्यप्रणाली',
    contact: 'संपर्क करें',
    changeLocation: 'स्थान बदलें',
    useGps: 'लाइव जीपीएस स्थान का उपयोग करें',
    gpsActive: 'जीपीएस सक्रिय',
    searchDistrict: 'जिला खोजें (उदा. भोपाल, पुणे)...',
    locationTelemetry: 'स्थान टेलीमेट्री',
    notifications: 'सूचनाएं',
    signOut: 'लॉग आउट',
    citizen: 'नागरिक',
    admin: 'व्यवस्थापक',
    welcomeBack: 'वापसी पर स्वागत है',
    signInPrompt: 'आपदानेत्र में जारी रखने के लिए साइन इन करें',
    adminAccess: 'सुरक्षित व्यवस्थापक पहुंच',
    mobileNumber: 'मोबाइल नंबर',
    enterMobile: '10 अंकों का मोबाइल नंबर दर्ज करें',
    mobileHelper: 'पंजीकृत 10-अंकीय भारतीय मोबाइल नंबर।',
    emailAddress: 'ईमेल पता',
    citizenEmail: 'नागरिक ईमेल पता',
    citizenEmailHelper: 'पंजीकृत नागरिक ईमेल पता।',
    adminId: 'व्यवस्थापक आईडी (12 वर्ण)',
    adminIdHelper: "प्रारूप: 'NETRA' + 7 अंक (उदा. NETRA0012121) अथवा आधिकारिक ईमेल",
    password: 'पासवर्ड',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    forgotAdminPassword: 'व्यवस्थापक पासवर्ड भूल गए?',
    signInWithMobile: 'मोबाइल नंबर से साइन इन करें',
    signInWithEmail: 'ईमेल से साइन इन करें',
    signInAsAdmin: 'व्यवस्थापक के रूप में साइन इन करें',
    authenticating: 'सत्यापित किया जा रहा है...',
    or: 'अथवा',
    signInGoogle: 'Google के साथ साइन इन करें',
    dontHaveAccount: 'खाता नहीं है?',
    createAccount: 'खाता बनाएं',
    saferPeople: 'सुरक्षित नागरिक | सुदृढ़ समुदाय',
    platformSubtitle: 'लोक सुरक्षा एवं आपातकालीन निर्णय समर्थन मंच',
    publicSafety: 'लोक सुरक्षा एवं आपातकालीन',
    decisionPlatform: 'निर्णय समर्थन मंच',
    missionStatement: 'सुरक्षित, अधिक सशक्त भारत के लिए बुद्धिमत्तापूर्ण आपदा जोखिम प्रबंधन।',
    anticipateRisks: 'जोखिमों का पूर्वानुमान',
    anticipateHelper: 'डेटा-संचालित अंतर्दृष्टि',
    enableResponse: 'त्वरित प्रतिक्रिया',
    responseHelper: 'समन्वित कार्यवाही',
    buildCommunities: 'सुरक्षित समुदाय निर्माण',
    communitiesHelper: 'एक अधिक सशक्त कल',
    together: 'एकजुट',
    forASafer: 'सुरक्षित कल',
    tomorrow: 'के लिए',
    togetherSafer: 'सुरक्षित कल के लिए एकजुट',
    disasterIntelligence: 'आपदा बुद्धिमत्ता',
    selectLanguage: 'भाषा चुनें',
    footerResilient: 'एक अधिक सुरक्षित और सशक्त कल का निर्माण।',
    footerEmpowering: 'डेटा, बुद्धिमत्ता और समयोचित कार्यवाही द्वारा समुदायों का सशक्तिकरण।',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    allRightsReserved: '© 2026. सर्वाधिकार सुरक्षित।',

    // Sidebar
    aiDisasterIntelligence: 'एआई आपदा बुद्धिमत्ता',
    cmdIntelligence: 'कमांड और बुद्धिमत्ता',
    commandDashboard: 'कमांड डैशबोर्ड',
    liveDisasterMap: 'लाइव आपदा मानचित्र',
    aiEmergencyAssistant: 'एआई आपातकालीन सहायक',
    analyticsPredictions: 'एनालिटिक्स एवं पूर्वानुमान',
    citizenReports: 'नागरिक रिपोर्ट',
    temporalForecasts: 'समयबद्ध पूर्वानुमान',
    riskAnalysis: 'जोखिम विश्लेषण (XAI)',
    whatIfSimulation: '"क्या होगा अगर?" सिमुलेशन',
    operationsRelocation: 'संचालन एवं स्थानांतरण',
    vulnerableHabitations: 'संवेदनशील बस्तियां',
    shelterCapacity: 'आश्रय क्षमता',
    relocationPlans: 'स्थानांतरण योजनाएं',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    system: 'सिस्टम',
    systemReports: 'सिस्टम रिपोर्ट',
    settings: 'सेटिंग्स',

    // Dashboard
    crisisDecisionCockpit: 'संकट निर्णय कॉकपिट',
    welcomeBackUser: 'वापसी पर स्वागत है',
    monitoring: 'निगरानी',
    live: 'लाइव',
    liveMap: 'लाइव मानचित्र',
    quickActions: 'त्वरित कार्रवाइयां',
    citizenReportsCard: 'नागरिक रिपोर्ट',
    emergencyContacts: 'आपातकालीन संपर्क',
    shelterCapacityCard: 'आश्रय क्षमता',
    earlyWarnings: 'प्रारंभिक चेतावनी',
    simulationCard: 'क्या अगर? सिमुलेशन',
    currentSituation: 'वर्तमान स्थिति',
    activeAlerts: 'सक्रिय चेतावनियां',
    critical: 'गंभीर',
    sheltersReady: 'आश्रय स्थल तैयार',
    operational: 'परिचालन में',
    bedOccupancy: 'बिस्तर अधिभोग',
    operationalDesk: 'परिचालन डेस्क',
    populationAtRisk: 'जोखिम में जनसंख्या',
    threatLevel: 'खतरा स्तर',
    activeSectors: 'सक्रिय क्षेत्र',
    riskDistribution: 'जोखिम वितरण',
    totalZones: 'कुल क्षेत्र',
    lowRisk: 'निम्न जोखिम',
    mediumRisk: 'मध्यम जोखिम',
    highRisk: 'उच्च जोखिम',
    viewFullRiskAnalysis: 'पूर्ण जोखिम विश्लेषण देखें',
    riskScoreTrend: '24-घंटे का जोखिम स्कोर रुझान',
    detailedTrendAnalysis: 'विस्तृत रुझान विश्लेषण',
    recentAlerts: 'हाल की चेतावनियां',
    viewAll: 'सभी देखें',
    aiAssistant: 'एआई सहायक'
  },
  bn: {
    appTitle: 'আপদানেত্র সংকট সিদ্ধান্ত সহায়তা',
    appSubtitle: 'রিয়েল-টাইম ভূ-স্থানীয় বুদ্ধিমত্তা • এআই পূর্বাভাস • জরুরি সহায়তা',
    home: 'হোম',
    about: 'আমাদের সম্পর্কে',
    howItWorks: 'পদ্ধতি',
    contact: 'যোগাযোগ',
    changeLocation: 'অবস্থান পরিবর্তন',
    useGps: 'লাইভ জিপিএস অবস্থান ব্যবহার করুন',
    gpsActive: 'জিপিএস সক্রিয়',
    searchDistrict: 'জেলা খুঁজুন (যেমন কলকাতা, বাঁকুড়া)...',
    locationTelemetry: 'অবস্থান টেলিমেট্রি',
    notifications: 'বিজ্ঞপ্তি',
    signOut: 'লগআউট',
    citizen: 'নাগরিক',
    admin: 'প্রশাসক',
    welcomeBack: 'স্বাগতম',
    signInPrompt: 'আপদানেত্রতে চালিয়ে যেতে সাইন ইন করুন',
    adminAccess: 'নিরাপদ প্রশাসক অ্যাক্সেস',
    mobileNumber: 'মোবাইল নম্বর',
    enterMobile: '১০ সংখ্যার মোবাইল নম্বর লিখুন',
    mobileHelper: 'নিবন্ধিত ভারতীয় মোবাইল নম্বর।',
    emailAddress: 'ইমেইল ঠিকানা',
    citizenEmail: 'নাগরিক ইমেইল ঠিকানা',
    citizenEmailHelper: 'নিবন্ধিত নাগরিক ইমেইল ঠিকানা।',
    adminId: 'অ্যাডমিন আইডি',
    adminIdHelper: "ফরম্যাট: 'NETRA' + ৭ অঙ্ক",
    password: 'পাসওয়ার্ড',
    enterPassword: 'পাসওয়ার্ড লিখুন',
    rememberMe: 'আমাকে মনে রাখুন',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    forgotAdminPassword: 'অ্যাডমিন পাসওয়ার্ড ভুলে গেছেন?',
    signInWithMobile: 'মোবাইল দিয়ে সাইন ইন করুন',
    signInWithEmail: 'ইমেইল দিয়ে সাইন ইন করুন',
    signInAsAdmin: 'প্রশাসক হিসাবে সাইন ইন করুন',
    authenticating: 'যাচাই করা হচ্ছে...',
    or: 'অথবা',
    signInGoogle: 'গুগল দিয়ে সাইন ইন করুন',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    saferPeople: 'নিরাপদ মানুষ | শক্তিশালী সমাজ',
    platformSubtitle: 'জননিরাপত্তা ও জরুরি সিদ্ধান্ত সহায়তা প্ল্যাটফর্ম',
    publicSafety: 'জননিরাপত্তা ও জরুরি',
    decisionPlatform: 'সিদ্ধান্ত সহায়তা প্ল্যাটফর্ম',
    missionStatement: 'একটি নিরাপদ ও স্থিতিশীল ভারতের জন্য দুর্যোগ ঝুঁকি ব্যবস্থাপনা।',
    anticipateRisks: 'ঝুঁকি পূর্বাভাস',
    anticipateHelper: 'উপাত্তভিত্তিক তথ্য',
    enableResponse: 'দ্রুত সাড়া প্রদান',
    responseHelper: 'সমন্বিত পদক্ষেপ',
    buildCommunities: 'নিরাপদ সমাজ গঠন',
    communitiesHelper: 'একটি উজ্জ্বল ভবিষ্যৎ',
    together: 'একসাথে',
    forASafer: 'নিরাপদ আগামী',
    tomorrow: 'দিনের জন্য',
    togetherSafer: 'নিরাপদ আগামীর জন্য একসাথে',
    disasterIntelligence: 'দুর্যোগ বুদ্ধিমত্তা',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    footerResilient: 'একটি নিরাপদ ও শক্তিশালী ভবিষ্যৎ গড়ে তোলা।',
    footerEmpowering: 'সময়োপযোগী তথ্য ও প্রযুক্তির মাধ্যমে ক্ষমতায়ন।',
    privacyPolicy: 'গোপনীয়তা নীতি',
    termsOfService: 'পরিষেবার শর্তাবলী',
    allRightsReserved: '© ২০২৬ সর্বস্বত্ব সংরক্ষিত।',

    // Sidebar
    aiDisasterIntelligence: 'এআই দুর্যোগ বুদ্ধিমত্তা',
    cmdIntelligence: 'কমান্ড ও বুদ্ধিমত্তা',
    commandDashboard: 'কমান্ড ড্যাশবোর্ড',
    liveDisasterMap: 'লাইভ দুর্যোগ মানচিত্র',
    aiEmergencyAssistant: 'এআই জরুরি সহকারী',
    analyticsPredictions: 'বিশ্লেষণ ও পূর্বাভাস',
    citizenReports: 'নাগরিক রিপোর্ট',
    temporalForecasts: 'সময়ভিত্তিক পূর্বাভাস',
    riskAnalysis: 'ঝুঁকি বিশ্লেষণ (XAI)',
    whatIfSimulation: '"যদি এমন হয়?" সিমুলেশন',
    operationsRelocation: 'অপারেশন ও স্থানান্তর',
    vulnerableHabitations: 'ঝুঁকিপূর্ণ জনবসতি',
    shelterCapacity: 'আশ্রয়কেন্দ্র ধারণক্ষমতা',
    relocationPlans: 'স্থানান্তর পরিকল্পনা',
    userManagement: 'ব্যবহারকারী ব্যবস্থাপনা',
    system: 'সিস্টেম',
    systemReports: 'সিস্টেম রিপোর্ট',
    settings: 'সেটিংস',

    // Dashboard
    crisisDecisionCockpit: 'সংকট সিদ্ধান্ত ককপিট',
    welcomeBackUser: 'স্বাগতম',
    monitoring: 'পর্যবেক্ষণ',
    live: 'লাইভ',
    liveMap: 'লাইভ মানচিত্র',
    quickActions: 'দ্রুত পদক্ষেপ',
    citizenReportsCard: 'নাগরিক রিপোর্ট',
    emergencyContacts: 'জরুরি যোগাযোগ',
    shelterCapacityCard: 'আশ্রয়কেন্দ্র ক্ষমতা',
    earlyWarnings: 'আগাম সতর্কবার্তা',
    simulationCard: 'কি হবে যদি? সিমুলেশন',
    currentSituation: 'বর্তমান পরিস্থিতি',
    activeAlerts: 'সক্রিয় সতর্কতা',
    critical: 'সংকটজনক',
    sheltersReady: 'প্রস্তুত আশ্রয়কেন্দ্র',
    operational: 'সক্রিয়',
    bedOccupancy: 'শয্যা দখল',
    operationalDesk: 'অপারেশনাল ডেস্ক',
    populationAtRisk: 'ঝুঁকিতে থাকা জনসংখ্যা',
    threatLevel: 'হুমকি মাত্রা',
    activeSectors: 'সক্রিয় সেক্টর',
    riskDistribution: 'ঝুঁকি বণ্টন',
    totalZones: 'মোট জোন',
    lowRisk: 'কম ঝুঁকি',
    mediumRisk: 'মাঝারি ঝুঁকি',
    highRisk: 'উচ্চ ঝুঁকি',
    viewFullRiskAnalysis: 'সম্পূর্ণ বিশ্লেষণ দেখুন',
    riskScoreTrend: '২৪ ঘণ্টার ঝুঁকি স্কোর ট্রেন্ড',
    detailedTrendAnalysis: 'বিস্তারিত ট্রেন্ড বিশ্লেষণ',
    recentAlerts: 'সাম্প্রতিক সতর্কতা',
    viewAll: 'সব দেখুন',
    aiAssistant: 'এআই সহকারী'
  },
  te: {
    appTitle: 'ఆపదనేత్ర విపత్తు నిర్ణయ మద్దతు',
    appSubtitle: 'నిజ-సమయ జియోస్పేషియల్ సమాచారం • ఏఐ అంచనాలు • అత్యవసర మార్గదర్శనం',
    home: 'హోమ్',
    about: 'మా గురించి',
    howItWorks: 'ఎలా పనిచేస్తుంది',
    contact: 'సంప్రదించండి',
    changeLocation: 'స్థానాన్ని మార్చండి',
    useGps: 'నా లైవ్ జీపీఎస్ ఉపయోగించండి',
    gpsActive: 'జీపీఎస్ సక్రియం',
    searchDistrict: 'జిల్లాను వెతకండి (ఉదా. విశాఖపట్నం, విజయవాడ)...',
    locationTelemetry: 'లొకేషన్ టెలిమెట్రీ',
    notifications: 'నోటిఫికేషన్లు',
    signOut: 'లాగ్ అవుట్',
    citizen: 'పౌరుడు',
    admin: 'నిర్వాహకుడు',
    welcomeBack: 'స్వాగతం',
    signInPrompt: 'ఆపదనేత్రకు కొనసాగడానికి సైన్ ఇన్ చేయండి',
    adminAccess: 'సురక్షిత అడ్మిన్ యాక్సెస్',
    mobileNumber: 'మొబైల్ సంఖ్య',
    enterMobile: '10 అంకెల మొబైల్ సంఖ్య నమోదు చేయండి',
    mobileHelper: 'రిజిస్టర్డ్ భారతీయ మొబైల్ సంఖ్య.',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    citizenEmail: 'పౌర ఈమెయిల్ చిరునామా',
    citizenEmailHelper: 'రిజిస్టర్డ్ పౌర ఈమెయిల్.',
    adminId: 'అడ్మిన్ ఐడీ',
    adminIdHelper: "ఫార్మాట్: 'NETRA' + 7 అంకెలు",
    password: 'పాస్‌వర్డ్',
    enterPassword: 'పాస్‌వర్డ్ నమోదు చేయండి',
    rememberMe: 'నన్ను గుర్తుంచుకో',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    forgotAdminPassword: 'అడ్మిన్ పాస్‌వర్డ్ మర్చిపోయారా?',
    signInWithMobile: 'మొబైల్ తో సైన్ ఇన్ చేయండి',
    signInWithEmail: 'ఈమెయిల్ తో సైన్ ఇన్ చేయండి',
    signInAsAdmin: 'అడ్మిన్ గా సైన్ ఇన్ చేయండి',
    authenticating: 'ప్రామాణీకరిస్తోంది...',
    or: 'లేదా',
    signInGoogle: 'గూగుల్ తో సైన్ ఇన్ చేయండి',
    dontHaveAccount: 'ఖాతా లేదా?',
    createAccount: 'ఖాతా సృష్టించండి',
    saferPeople: 'సురక్షిత ప్రజలు | దృఢమైన సమాజం',
    platformSubtitle: 'ప్రజా భద్రత & అత్యవసర నిర్ణయ మద్దతు వేదిక',
    publicSafety: 'ప్రజా భద్రత & అత్యవసర',
    decisionPlatform: 'నిర్ణయ మద్దతు వేదిక',
    missionStatement: 'మరింత సురక్షితమైన భారతదేశం కోసం తెలివైన విపత్తు నిర్వహణ.',
    anticipateRisks: 'ప్రమాదాలను ముందే ఊహించండి',
    anticipateHelper: 'డేటా ఆధారిత విశ్లేషణ',
    enableResponse: 'వేగవంతమైన స్పందన',
    responseHelper: 'సమన్వయ చర్యలు',
    buildCommunities: 'సురక్షిత సమాజాల నిర్మాణం',
    communitiesHelper: 'మంచి భవిష్యత్తు కోసం',
    together: 'కలిసికట్టుగా',
    forASafer: 'సురక్షిత రేపటి',
    tomorrow: 'కోసం',
    togetherSafer: 'సురక్షిత రేపటి కోసం కలిసికట్టుగా',
    disasterIntelligence: 'విపత్తు ఇంటెలిజెన్స్',
    selectLanguage: 'భాషను ఎంచుకోండి',
    footerResilient: 'సురక్షితమైన మరియు బలమైన రేపటి నిర్మాణం.',
    footerEmpowering: 'సకాల చర్యలతో సమాజాన్ని శక్తివంతం చేయడం.',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfService: 'సేవా నిబంధనలు',
    allRightsReserved: '© 2026. సర్వహక్కులు ప్రత్యేకించబడ్డాయి.',

    // Sidebar
    aiDisasterIntelligence: 'ఏఐ విపత్తు ఇంటెలిజెన్స్',
    cmdIntelligence: 'కమాండ్ & ఇంటెలిజెన్స్',
    commandDashboard: 'కమాండ్ డ్యాష్‌బోర్డ్',
    liveDisasterMap: 'లైవ్ విపత్తు మ్యాప్',
    aiEmergencyAssistant: 'ఏఐ అత్యవసర సహాయకుడు',
    analyticsPredictions: 'విశ్లేషణలు & అంచనాలు',
    citizenReports: 'పౌర నివేదికలు',
    temporalForecasts: 'సమయ ఆధారిత అంచనాలు',
    riskAnalysis: 'ప్రమాద విశ్లేషణ (XAI)',
    whatIfSimulation: '"ఒకవేళ జరిగితే?" సిమ్యులేషన్',
    operationsRelocation: 'ఆపరేషన్లు & పునరావాసం',
    vulnerableHabitations: 'ముప్పు ప్రాంత నివాసాలు',
    shelterCapacity: 'పునరావాస కేంద్రాల సామర్థ్యం',
    relocationPlans: 'పునరావాస ప్రణాళికలు',
    userManagement: 'వినియోగదారుల నిర్వహణ',
    system: 'సిస్టమ్',
    systemReports: 'సిస్టమ్ నివేదికలు',
    settings: 'సెట్టింగ్‌లు',

    // Dashboard
    crisisDecisionCockpit: 'విపత్తు నిర్ణయ కాక్‌పిట్',
    welcomeBackUser: 'స్వాగతం',
    monitoring: 'పర్యవేక్షణ',
    live: 'లైవ్',
    liveMap: 'లైవ్ మ్యాప్',
    quickActions: 'త్వరిత చర్యలు',
    citizenReportsCard: 'పౌర నివేదికలు',
    emergencyContacts: 'అత్యవసర కాంటాక్ట్‌లు',
    shelterCapacityCard: 'పునరావాస కేంద్రాల సామర్థ్యం',
    earlyWarnings: 'ముందస్తు హెచ్చరికలు',
    simulationCard: 'ఏమి జరగవచ్చు? సిమ్యులేషన్',
    currentSituation: 'ప్రస్తుత పరిస్థితి',
    activeAlerts: 'యాక్టివ్ హెచ్చరికలు',
    critical: 'తీవ్రమైనది',
    sheltersReady: 'సిద్ధంగా ఉన్న పునరావాసాలు',
    operational: 'కార్యనిర్వహణలో ఉంది',
    bedOccupancy: 'బెడ్ల వినియోగం',
    operationalDesk: 'ఆపరేషనల్ డెస్క్',
    populationAtRisk: 'ప్రమాదంలో ఉన్న జనాభా',
    threatLevel: 'ముప్పు స్థాయి',
    activeSectors: 'క్రియాశీల సెక్టార్లు',
    riskDistribution: 'ప్రమాద విభజన',
    totalZones: 'మొత్తం జోన్లు',
    lowRisk: 'తక్కువ ప్రమాదం',
    mediumRisk: 'మధ్యస్థ ప్రమాదం',
    highRisk: 'అధిక ప్రమాదం',
    viewFullRiskAnalysis: 'పూర్తి విశ్లేషణను చూడండి',
    riskScoreTrend: '24-గంటల ప్రమాద స్కోరు ట్రెండ్',
    detailedTrendAnalysis: 'వివరణాత్మక ట్రెండ్ విశ్లేషణ',
    recentAlerts: 'ఇటీవలి హెచ్చరికలు',
    viewAll: 'అన్నీ చూడండి',
    aiAssistant: 'ఏఐ అసిస్టెంట్'
  },
  mr: {
    appTitle: 'आपदानेत्र आपत्कालीन निर्णय सहाय्य',
    appSubtitle: 'रिअल-टाइम भौगोलिक बुद्धिमत्ता • एआय अंदाज • आणीबाणी मार्गदर्शन',
    home: 'मुख्यपृष्ठ',
    about: 'आमच्याबद्दल',
    howItWorks: 'कसे कार्य करते',
    contact: 'संपर्क',
    changeLocation: 'स्थान बदला',
    useGps: 'माझे थेट जीपीएस स्थान वापरा',
    gpsActive: 'जीपीएस सक्रिय',
    searchDistrict: 'जिल्हा शोधा (उदा. मुंबई, पुणे)...',
    locationTelemetry: 'स्थान टेलीमेट्री',
    notifications: 'सूचना',
    signOut: 'लॉग आऊट',
    citizen: 'नागरिक',
    admin: 'प्रशासक',
    welcomeBack: 'पुन्हा स्वागत आहे',
    signInPrompt: 'आपदानेत्र सुरू ठेवण्यासाठी साइन इन करा',
    adminAccess: 'सुरक्षित प्रशासक प्रवेश',
    mobileNumber: 'मोबाईल क्रमांक',
    enterMobile: '१० अंकी मोबाईल क्रमांक टाका',
    mobileHelper: 'नोंदणीकृत १० अंकी भारतीय मोबाईल क्रमांक.',
    emailAddress: 'ईमेल पत्ता',
    citizenEmail: 'नागरिक ईमेल पत्ता',
    citizenEmailHelper: 'नोंदणीकृत नागरिक ईमेल पत्ता.',
    adminId: 'अॅडमिन आयडी',
    adminIdHelper: "नियम: 'NETRA' + ७ अंक",
    password: 'पासवर्ड',
    enterPassword: 'पासवर्ड टाका',
    rememberMe: 'मला लक्षात ठेवा',
    forgotPassword: 'पासवर्ड विसरलात?',
    forgotAdminPassword: 'अॅडमिन पासवर्ड विसरलात?',
    signInWithMobile: 'मोबाईलने साइन इन करा',
    signInWithEmail: 'ईमेलने साइन इन करा',
    signInAsAdmin: 'प्रशासक म्हणून साइन इन करा',
    authenticating: 'प्रमाणीकरण चालू आहे...',
    or: 'किंवा',
    signInGoogle: 'Google सह साइन इन करा',
    dontHaveAccount: 'खाते नाही?',
    createAccount: 'खाते तयार करा',
    saferPeople: 'सुरक्षित नागरिक | सक्षम समाज',
    platformSubtitle: 'सार्वजनिक सुरक्षा आणि आपत्कालीन निर्णय समर्थन मंच',
    publicSafety: 'सार्वजनिक सुरक्षा आणि आपत्कालीन',
    decisionPlatform: 'निर्णय समर्थन मंच',
    missionStatement: 'सुरक्षित आणि सक्षम भारतासाठी प्रगत आपत्ती जोखीम व्यवस्थापन.',
    anticipateRisks: 'जोखमींचा अंदाज घ्या',
    anticipateHelper: 'डेटा-चालित माहिती',
    enableResponse: 'जलद प्रतिसाद द्या',
    responseHelper: 'समन्वित कृती',
    buildCommunities: 'सुरक्षित समुदाय बनवा',
    communitiesHelper: 'उद्याच्या सुरक्षित भविष्यासाठी',
    together: 'एकत्रित',
    forASafer: 'सुरक्षित उद्याच्या',
    tomorrow: 'साठी',
    togetherSafer: 'सुरक्षित भविष्यासाठी एकत्र',
    disasterIntelligence: 'आपत्ती बुद्धिमत्ता',
    selectLanguage: 'भाषा निवडा',
    footerResilient: 'सुरक्षित आणि सक्षम उद्याची निर्मिती.',
    footerEmpowering: 'डेटा आणि वेळेवर कारवाईद्वारे समुदायांचे सक्षमीकरण.',
    privacyPolicy: 'गोपनीयता धोरण',
    termsOfService: 'सेवा अटी',
    allRightsReserved: '© 2026. सर्व हक्क राखीव.',

    // Sidebar
    aiDisasterIntelligence: 'एआय आपत्ती बुद्धिमत्ता',
    cmdIntelligence: 'कमांड आणि बुद्धिमत्ता',
    commandDashboard: 'कमांड डॅशबोर्ड',
    liveDisasterMap: 'थेट आपत्ती नकाशा',
    aiEmergencyAssistant: 'एआय आपत्कालीन सहाय्यक',
    analyticsPredictions: 'विश्लेषण आणि अंदाज',
    citizenReports: 'नागरिक अहवाल',
    temporalForecasts: 'वेळेनुसार अंदाज',
    riskAnalysis: 'जोखीम विश्लेषण (XAI)',
    whatIfSimulation: '"काय घडेल जर?" सिम्युलेशन',
    operationsRelocation: 'ऑपरेशन्स आणि स्थलांतर',
    vulnerableHabitations: 'संवेदनशील वस्त्या',
    shelterCapacity: 'निवारा क्षमता',
    relocationPlans: 'स्थलांतर योजना',
    userManagement: 'वापरकर्ता व्यवस्थापन',
    system: 'प्रणाली',
    systemReports: 'प्रणाली अहवाल',
    settings: 'सेटिंग्ज',

    // Dashboard
    crisisDecisionCockpit: 'आपत्ती निर्णय कॉकपिट',
    welcomeBackUser: 'स्वागत आहे',
    monitoring: 'निरीक्षण',
    live: 'थेट',
    liveMap: 'थेट नकाशा',
    quickActions: 'जलद कृती',
    citizenReportsCard: 'नागरिक अहवाल',
    emergencyContacts: 'आपत्कालीन संपर्क',
    shelterCapacityCard: 'निवारा क्षमता',
    earlyWarnings: 'पूर्वसूचना',
    simulationCard: 'काय घडेल जर? सिम्युलेशन',
    currentSituation: 'सद्यस्थिती',
    activeAlerts: 'सक्रिय सतर्कता',
    critical: 'गंभीर',
    sheltersReady: 'तयार निवारे',
    operational: 'कार्यरत',
    bedOccupancy: 'बेड वापर',
    operationalDesk: 'ऑपरेशनल डेस्क',
    populationAtRisk: 'धोक्यात असलेली लोकसंख्या',
    threatLevel: 'धोका पातळी',
    activeSectors: 'सक्रिय क्षेत्रे',
    riskDistribution: 'जोखीम वितरण',
    totalZones: 'एकूण क्षेत्रे',
    lowRisk: 'कमी जोखीम',
    mediumRisk: 'मध्यम जोखीम',
    highRisk: 'उच्च जोखीम',
    viewFullRiskAnalysis: 'संपूर्ण विश्लेषण पहा',
    riskScoreTrend: '२४-तास जोखीम स्कोर कल',
    detailedTrendAnalysis: 'तपशीलवार कल विश्लेषण',
    recentAlerts: 'अलीकडील सतर्कता',
    viewAll: 'सर्व पहा',
    aiAssistant: 'एआय सहाय्यक'
  },
  ta: {
    appTitle: 'ஆபதாநேத்ரா அவசரகால முடிவு ஆதரவு',
    appSubtitle: 'நேரலை புவிசார் நுண்ணறிவு • ஏஐ முன்னறிவிப்பு • அவசர வழிகாட்டுதல்',
    home: 'முகப்பு',
    about: 'எங்களை பற்றி',
    howItWorks: 'செயல்முறை',
    contact: 'தொடர்பு',
    changeLocation: 'இருப்பிடம் மாற்றுக',
    useGps: 'என் ஜிபிஎஸ் இருப்பிடத்தைப் பயன்படுத்து',
    gpsActive: 'ஜிபிஎஸ் செயலில்',
    searchDistrict: 'மாவட்டத்தைத் தேடுக (எ.கா. சென்னை, மதுரை)...',
    locationTelemetry: 'இருப்பிட தொலைஅளவியல்',
    notifications: 'அறிவிப்புகள்',
    signOut: 'வெளியேறு',
    citizen: 'குடிமகன்',
    admin: 'நிர்வாகி',
    welcomeBack: 'நல்வரவு',
    signInPrompt: 'தொடர உள்நுழைக',
    adminAccess: 'பாதுகாப்பான நிர்வாக அணுகல்',
    mobileNumber: 'கைபேசி எண்',
    enterMobile: '10 இலக்க கைபேசி எண் உள்ளிடுக',
    mobileHelper: 'பதிவுசெய்யப்பட்ட கைபேசி எண்.',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    citizenEmail: 'குடிமகன் மின்னஞ்சல்',
    citizenEmailHelper: 'பதிவுசெய்யப்பட்ட குடிமகன் மின்னஞ்சல்.',
    adminId: 'நிர்வாகி ஐடி',
    adminIdHelper: "வடிவம்: 'NETRA' + 7 இலக்கங்கள்",
    password: 'கடவுச்சொல்',
    enterPassword: 'கடவுச்சொல் உள்ளிடுக',
    rememberMe: 'என்னை நினைவில் கொள்க',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    forgotAdminPassword: 'நிர்வாகி கடவுச்சொல் மறந்துவிட்டதா?',
    signInWithMobile: 'கைபேசி மூலம் உள்நுழைக',
    signInWithEmail: 'மின்னஞ்சல் மூலம் உள்நுழைக',
    signInAsAdmin: 'நிர்வாகியாக உள்நுழைக',
    authenticating: 'சரிபார்க்கிறது...',
    or: 'அல்லது',
    signInGoogle: 'Google மூலம் உள்நுழைக',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    createAccount: 'கணக்கு உருவாக்குக',
    saferPeople: 'பாதுகாப்பான மக்கள் | வலிமையான சமூகம்',
    platformSubtitle: 'பொது பாதுகாப்பு & அவசரகால முடிவு ஆதரவு தளம்',
    publicSafety: 'பொது பாதுகாப்பு & அவசரகால',
    decisionPlatform: 'முடிவு ஆதரவு தளம்',
    missionStatement: 'பாதுகாப்பான இந்தியாவிற்கான பேரிடர் இடர் மேலாண்மை.',
    anticipateRisks: 'ஆபத்துகளை கணிக்கவும்',
    anticipateHelper: 'தரவு அடிப்படையிலான நுண்ணறிவு',
    enableResponse: 'விரைவான நடவடிக்கை',
    responseHelper: 'ஒருங்கிணைந்த செயல்பாடு',
    buildCommunities: 'பாதுகாப்பான சமுதாயம்',
    communitiesHelper: 'சிறந்த நாளைய விடியலுக்காக',
    together: 'ஒன்றாக',
    forASafer: 'பாதுகாப்பான',
    tomorrow: 'நாளைக்காக',
    togetherSafer: 'பாதுகாப்பான நாளைக்காக ஒன்றிணைவோம்',
    disasterIntelligence: 'பேரிடர் நுண்ணறிவு',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    footerResilient: 'பாதுகாப்பான, நிலையான நாளையை உருவாக்குதல்.',
    footerEmpowering: 'சரியான தரவுகள் மூலம் சமூகங்களை மேம்படுத்துதல்.',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',
    allRightsReserved: '© 2026. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',

    // Sidebar
    aiDisasterIntelligence: 'ஏஐ பேரிடர் நுண்ணறிவு',
    cmdIntelligence: 'கட்டளை & நுண்ணறிவு',
    commandDashboard: 'கட்டளை கட்டுப்பாட்டு அறை',
    liveDisasterMap: 'நேரலை பேரிடர் வரைபடம்',
    aiEmergencyAssistant: 'ஏஐ அவசர உதவியாளர்',
    analyticsPredictions: 'பகுப்பாய்வு & கணிப்புகள்',
    citizenReports: 'பொதுமக்கள் புகார்கள்',
    temporalForecasts: 'காலநிலை முன்னறிவிப்புகள்',
    riskAnalysis: 'இடர் பகுப்பாய்வு (XAI)',
    whatIfSimulation: '"ஒருவேளை நடந்தால்?" உருவகப்படுத்துதல்',
    operationsRelocation: 'நடவடிக்கைகள் & இடமாற்றம்',
    vulnerableHabitations: 'பாதிக்கப்படக்கூடிய பகுதிகள்',
    shelterCapacity: 'நிவாரண முகாம் கொள்ளளவு',
    relocationPlans: 'இடம்பெயர்வு திட்டங்கள்',
    userManagement: 'பயனர் மேலாண்மை',
    system: 'கணினி',
    systemReports: 'கணினி அறிக்கைகள்',
    settings: 'அமைப்புகள்',

    // Dashboard
    crisisDecisionCockpit: 'பேரிடர் முடிவு தளம்',
    welcomeBackUser: 'நல்வரவு',
    monitoring: 'கண்காணிப்பு',
    live: 'நேரலை',
    liveMap: 'நேரலை வரைபடம்',
    quickActions: 'விரைவு நடவடிக்கைகள்',
    citizenReportsCard: 'பொதுமக்கள் அறிக்கைகள்',
    emergencyContacts: 'அவசர தொடர்புகள்',
    shelterCapacityCard: 'முகாம் கொள்ளளவு',
    earlyWarnings: 'முன்னெச்சரிக்கைகள்',
    simulationCard: 'என்ன நடக்கும்? மாதிரி',
    currentSituation: 'தற்போதைய நிலை',
    activeAlerts: 'செயலில் உள்ள எச்சரிக்கைகள்',
    critical: 'மிக முக்கியமானது',
    sheltersReady: 'தயாராக உள்ள முகாம்கள்',
    operational: 'இயங்குகிறது',
    bedOccupancy: 'படுக்கை பயன்பாடு',
    operationalDesk: 'இயக்க மையம்',
    populationAtRisk: 'ஆபத்தில் உள்ள மக்கள்',
    threatLevel: 'அச்சுறுத்தல் அளவு',
    activeSectors: 'செயலில் உள்ள பகுதிகள்',
    riskDistribution: 'இடர் பகிர்வு',
    totalZones: 'மொத்த மண்டலங்கள்',
    lowRisk: 'குறைந்த ஆபத்து',
    mediumRisk: 'நடுத்தர ஆபத்து',
    highRisk: 'அதிக ஆபத்து',
    viewFullRiskAnalysis: 'முழு ஆய்வை காண்க',
    riskScoreTrend: '24-மணி நேர இடர் போக்கு',
    detailedTrendAnalysis: 'விரிவான போக்கு ஆய்வு',
    recentAlerts: 'சமீபத்திய எச்சரிக்கைகள்',
    viewAll: 'அனைத்தையும் காண்க',
    aiAssistant: 'ஏஐ உதவியாளர்'
  },
  gu: {
    appTitle: 'આપદાનેત્ર આપત્તિ નિર્ણય સહાય',
    appSubtitle: 'રીઅલ-ટાઇમ ભૌગોલિક ઇન્ટેલિજન્સ • એઆઈ આગાહી • કટોકટી માર્ગદર્શન',
    home: 'હોમ',
    about: 'અમારા વિશે',
    howItWorks: 'કેવી રીતે કાર્ય કરે છે',
    contact: 'સંપર્ક',
    changeLocation: 'સ્થાન બદલો',
    useGps: 'મારું જીપીએસ વાપરો',
    gpsActive: 'જીપીએસ સક્રિય',
    searchDistrict: 'જિલ્લો શોધો (દા.ત. અમદાવાદ, સુરત)...',
    locationTelemetry: 'સ્થાન ટેલિમેટ્રી',
    notifications: 'સૂચનાઓ',
    signOut: 'લૉગ આઉટ',
    citizen: 'નાગરિક',
    admin: 'વહીવટકર્તા',
    welcomeBack: 'સ્વાગત છે',
    signInPrompt: 'ચાલુ રાખવા માટે સાઇન ઇન કરો',
    adminAccess: 'સુરક્ષિત એડમિન ઍક્સેસ',
    mobileNumber: 'મોબાઇલ નંબર',
    enterMobile: '૧૦ અંકનો મોબાઇલ નંબર દાખલ કરો',
    mobileHelper: 'નોંધાયેલ ૧૦ અંકનો ભારતીય મોબાઇલ નંબર.',
    emailAddress: 'ઈમેલ સરનામું',
    citizenEmail: 'નાગરિક ઈમેલ સરનામું',
    citizenEmailHelper: 'નોંધાયેલ નાગરિક ઈમેલ.',
    adminId: 'એડમિન આઈડી',
    adminIdHelper: "ફોર્મેટ: 'NETRA' + 7 અંકો",
    password: 'પાસવર્ડ',
    enterPassword: 'પાસવર્ડ દાખલ કરો',
    rememberMe: 'મને યાદ રાખો',
    forgotPassword: 'પાસવર્ડ ભૂલી ગયા?',
    forgotAdminPassword: 'એડમિન પાસવર્ડ ભૂલી ગયા?',
    signInWithMobile: 'મોબાઇલથી સાઇન ઇન કરો',
    signInWithEmail: 'ઈમેલથી સાઇન ઇન કરો',
    signInAsAdmin: 'એડમિન તરીકે સાઇન ઇન કરો',
    authenticating: 'પ્રમાણિત કરી રહ્યું છે...',
    or: 'અથવા',
    signInGoogle: 'Google સાથે સાઇન ઇન કરો',
    dontHaveAccount: 'ખાતું નથી?',
    createAccount: 'ખાતું બનાવો',
    saferPeople: 'સુરક્ષિત લોકો | મજબૂત સમુદાય',
    platformSubtitle: 'જાહેર સલામતી અને કટોકટી નિર્ણય સહાય પ્લેટફોર્મ',
    publicSafety: 'જાહેર સલામતી અને કટોકટી',
    decisionPlatform: 'નિર્ણય સહાય પ્લેટફોર્મ',
    missionStatement: 'સુરક્ષિત ભારત માટે આપત્તિ જોખમ વ્યવસ્થાપન.',
    anticipateRisks: 'જોખમોની આગાહી કરો',
    anticipateHelper: 'ડેટા-સંચાલિત માહિતી',
    enableResponse: 'ઝડપી પ્રતિસાદ',
    responseHelper: 'સંકલિત પગલાં',
    buildCommunities: 'સુરક્ષિત સમુદાય બનાવો',
    communitiesHelper: 'વધુ સુરક્ષિત આવતીકાલ માટે',
    together: 'એકસાથે',
    forASafer: 'સુરક્ષિત આવતીકાલ',
    tomorrow: 'માટે',
    togetherSafer: 'સુરક્ષિત આવતીકાલ માટે સાથે',
    disasterIntelligence: 'આપત્તિ ઇન્ટેલિજન્સ',
    selectLanguage: 'ભાષા પસંદ કરો',
    footerResilient: 'સુરક્ષિત અને સક્ષમ આવતીકાલનું નિર્માણ.',
    footerEmpowering: 'ડેટા અને સમયસર પગલાં દ્વારા સમુદાયોનું સશક્તિકરણ.',
    privacyPolicy: 'ગોપનીયતા નીતિ',
    termsOfService: 'સેવાની શરતો',
    allRightsReserved: '© 2026. સર્વાધિકાર સુરક્ષિત.',

    // Sidebar
    aiDisasterIntelligence: 'એઆઈ આપત્તિ ઇન્ટેલિજન્સ',
    cmdIntelligence: 'કમાન્ડ અને ઇન્ટેલિજન્સ',
    commandDashboard: 'કમાન્ડ ડેશબોર્ડ',
    liveDisasterMap: 'લાઈવ આપત્તિ નકશો',
    aiEmergencyAssistant: 'એઆઈ કટોકટી સહાયક',
    analyticsPredictions: 'વિશ્લેષણ અને આગાહી',
    citizenReports: 'નાગરિક અહેવાલો',
    temporalForecasts: 'સમય આધારિત આગાહી',
    riskAnalysis: 'જોખમ વિશ્લેષણ (XAI)',
    whatIfSimulation: '"જો આમ થાય તો?" સિમ્યુલેશન',
    operationsRelocation: 'ઓપરેશન્સ અને સ્થળાંતર',
    vulnerableHabitations: 'સંવેદનશીલ વસાહતો',
    shelterCapacity: 'આશ્રય ક્ષમતા',
    relocationPlans: 'સ્થળાંતર યોજનાઓ',
    userManagement: 'વપરાશકર્તા વ્યવસ્થાપન',
    system: 'સિસ્ટમ',
    systemReports: 'સિસ્ટમ રિપોર્ટ્સ',
    settings: 'સેટિંગ્સ',

    // Dashboard
    crisisDecisionCockpit: 'આપત્તિ નિર્ણય કોકપિટ',
    welcomeBackUser: 'સ્વાગત છે',
    monitoring: 'મોનિટરિંગ',
    live: 'લાઈવ',
    liveMap: 'લાઈવ નકશો',
    quickActions: 'ઝડપી પગલાં',
    citizenReportsCard: 'નાગરિક અહેવાલો',
    emergencyContacts: 'કટોકટી સંપર્કો',
    shelterCapacityCard: 'આશ્રય ક્ષમતા',
    earlyWarnings: 'પ્રારંભિક ચેતવણીઓ',
    simulationCard: 'જો આમ થાય તો? સિમ્યુલેશન',
    currentSituation: 'વર્તમાન પરિસ્થિતિ',
    activeAlerts: 'સક્રિય ચેતવણીઓ',
    critical: 'ગંભીર',
    sheltersReady: 'તૈયાર આશ્રયસ્થાનો',
    operational: 'કાર્યરત',
    bedOccupancy: 'બેડ વપરાશ',
    operationalDesk: 'ઓપરેશનલ ડેસ્ક',
    populationAtRisk: 'જોખમમાં મુકાયેલ વસ્તી',
    threatLevel: 'જોખમ સ્તર',
    activeSectors: 'સક્રિય સેક્ટર્સ',
    riskDistribution: 'જોખમ વિતરણ',
    totalZones: 'કુલ ઝોન',
    lowRisk: 'ઓછું જોખમ',
    mediumRisk: 'મધ્યમ જોખમ',
    highRisk: 'ઉચ્ચ જોખમ',
    viewFullRiskAnalysis: 'સંપૂર્ણ વિશ્લેષણ જુઓ',
    riskScoreTrend: '૨૪-કલાક જોખમ સ્કોર ટ્રેન્ડ',
    detailedTrendAnalysis: 'વિગતવાર ટ્રેન્ડ વિશ્લેષણ',
    recentAlerts: 'તાજેતરની ચેતવણીઓ',
    viewAll: 'બધું જુઓ',
    aiAssistant: 'એઆઈ સહાયક'
  },
  kn: {
    appTitle: 'ಆಪದನೇತ್ರ ವಿಪತ್ತು ನಿರ್ಧಾರ ಬೆಂಬಲ',
    appSubtitle: 'ನೈಜ-ಸಮಯದ ಭೌಗೋಳಿಕ ಮಾಹಿತಿ • ಎಐ ಮುನ್ಸೂಚನೆ • ತುರ್ತು ಮಾರ್ಗದರ್ಶನ',
    home: 'ಮುಖಪುಟ',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    howItWorks: 'ಕಾರ್ಯವಿಧಾನ',
    contact: 'ಸಂಪರ್ಕ',
    changeLocation: 'ಸ್ಥಳ ಬದಲಾಯಿಸಿ',
    useGps: 'ನನ್ನ ಲೈವ್ ಜಿಪಿಎಸ್ ಬಳಸಿ',
    gpsActive: 'ಜಿಪಿಎಸ್ ಸಕ್ರಿಯ',
    searchDistrict: 'ಜಿಲ್ಲೆಯನ್ನು ಹುಡುಕಿ (ಉದಾ. ಬೆಂಗಳೂರು, ಮೈಸೂರು)...',
    locationTelemetry: 'ಸ್ಥಳ ಟೆಲಿಮೆಟ್ರಿ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    signOut: 'ಸೈನ್ ಔಟ್',
    citizen: 'ನಾಗರಿಕ',
    admin: 'ನಿರ್ವಾಹಕ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    signInPrompt: 'ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    adminAccess: 'ಸುರಕ್ಷಿತ ಅಡ್ಮಿನ್ ಪ್ರವೇಶ',
    mobileNumber: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    enterMobile: '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    mobileHelper: 'ನೋಂದಾಯಿತ ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ.',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    citizenEmail: 'ನಾಗರಿಕ ಇಮೇಲ್ ವಿಳಾಸ',
    citizenEmailHelper: 'ನೋಂದಾಯಿತ ನಾಗರಿಕ ಇಮೇಲ್.',
    adminId: 'ಅಡ್ಮಿನ್ ಐಡಿ',
    adminIdHelper: "ಮಾದರಿ: 'NETRA' + 7 ಅಂಕಿಗಳು",
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    enterPassword: 'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    rememberMe: 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    forgotAdminPassword: 'ಅಡ್ಮಿನ್ ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    signInWithMobile: 'ಮೊಬೈಲ್ ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    signInWithEmail: 'ಇಮೇಲ್ ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    signInAsAdmin: 'ಅಡ್ಮಿನ್ ಆಗಿ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    authenticating: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    or: 'ಅಥವಾ',
    signInGoogle: 'ಗೂಗಲ್ ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    dontHaveAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    createAccount: 'ಖಾತೆ ತೆರೆಯಿರಿ',
    saferPeople: 'ಸುರಕ್ಷಿತ ಜನರು | ಬಲಿಷ್ಠ ಸಮುದಾಯ',
    platformSubtitle: 'ಸಾರ್ವಜನಿಕ ಸುರಕ್ಷತೆ ಮತ್ತು ತುರ್ತು ನಿರ್ಧಾರ ಬೆಂಬಲ ವೇದಿಕೆ',
    publicSafety: 'ಸಾರ್ವಜನಿಕ ಸುರಕ್ಷತೆ ಮತ್ತು ತುರ್ತು',
    decisionPlatform: 'ನಿರ್ಧಾರ ಬೆಂಬಲ ವೇದಿಕೆ',
    missionStatement: 'ಸುರಕ್ಷಿತ ಭಾರತಕ್ಕಾಗಿ ಬುದ್ಧಿವಂತ ವಿಪತ್ತು ನಿರ್ವಹಣೆ.',
    anticipateRisks: 'ಅಪಾಯಗಳನ್ನು ಊಹಿಸಿ',
    anticipateHelper: 'ಡೇಟಾ ಆಧಾರಿತ ಮಾಹಿತಿ',
    enableResponse: 'ತ್ವರಿತ ಪ್ರತಿಕ್ರಿಯೆ',
    responseHelper: 'ಸಂಘಟಿತ ಕ್ರಮ',
    buildCommunities: 'ಸುರಕ್ಷಿತ ಸಮುದಾಯಗಳ ನಿರ್ಮಾಣ',
    communitiesHelper: 'ಉತ್ತಮ ನಾಳೆಗಾಗಿ',
    together: 'ಒಟ್ಟಾಗಿ',
    forASafer: 'ಸುರಕ್ಷಿತ ನಾಳೆಗಾಗಿ',
    tomorrow: 'ಜೊತೆಯಾಗಿ',
    togetherSafer: 'ಸುರಕ್ಷಿತ ನಾಳೆಗಾಗಿ ಒಟ್ಟಾಗಿ',
    disasterIntelligence: 'ವಿಪತ್ತು ಇಂಟೆಲಿಜೆನ್ಸ್',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    footerResilient: 'ಸುರಕ್ಷಿತ ಮತ್ತು ಸಮರ್ಥ ನಾಳೆಯ ನಿರ್ಮಾಣ.',
    footerEmpowering: 'ಸಮಯೋಚಿತ ಮಾಹಿತಿಯೊಂದಿಗೆ ಸಮುದಾಯಗಳ ಸಬಲೀಕರಣ.',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    termsOfService: 'ಸೇವಾ ನಿಯಮಗಳು',
    allRightsReserved: '© 2026. ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',

    // Sidebar
    aiDisasterIntelligence: 'ಎಐ ವಿಪತ್ತು ಇಂಟೆಲಿಜೆನ್ಸ್',
    cmdIntelligence: 'ಕಮಾಂಡ್ ಮತ್ತು ಇಂಟೆಲಿಜೆನ್ಸ್',
    commandDashboard: 'ಕಮಾಂಡ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    liveDisasterMap: 'ಲೈವ್ ವಿಪತ್ತು ನಕ್ಷೆ',
    aiEmergencyAssistant: 'ಎಐ ತುರ್ತು ಸಹಾಯಕ',
    analyticsPredictions: 'ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಮುನ್ಸೂಚನೆಗಳು',
    citizenReports: 'ನಾಗರಿಕ ವರದಿಗಳು',
    temporalForecasts: 'ಸಮಯಾಧಾರಿತ ಮುನ್ಸೂಚನೆಗಳು',
    riskAnalysis: 'ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ (XAI)',
    whatIfSimulation: '"ಹೀಗಾದರೆ ಹೇಗೆ?" ಸಿಮ್ಯುಲೇಶನ್',
    operationsRelocation: 'ಕಾರ್ಯಾಚರಣೆ ಮತ್ತು ಸ್ಥಳಾಂತರ',
    vulnerableHabitations: 'ದುರ್ಬಲ ಆವಾಸಸ್ಥಾನಗಳು',
    shelterCapacity: 'ಆಶ್ರಯ ತಾಣಗಳ ಸಾಮರ್ಥ್ಯ',
    relocationPlans: 'ಸ್ಥಳಾಂತರ ಯೋಜನೆಗಳು',
    userManagement: 'ಬಳಕೆದಾರರ ನಿರ್ವಹಣೆ',
    system: 'ವ್ಯವಸ್ಥೆ',
    systemReports: 'ವ್ಯವಸ್ಥೆಯ ವರದಿಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',

    // Dashboard
    crisisDecisionCockpit: 'ವಿಪತ್ತು ನಿರ್ಧಾರ ಕಾಕ್‌ಪಿಟ್',
    welcomeBackUser: 'ಸ್ವಾಗತ',
    monitoring: 'ಮೇಲ್ವಿಚಾರಣೆ',
    live: 'ಲೈವ್',
    liveMap: 'ಲೈವ್ ನಕ್ಷೆ',
    quickActions: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    citizenReportsCard: 'ನಾಗರಿಕ ವರದಿಗಳು',
    emergencyContacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    shelterCapacityCard: 'ಆಶ್ರಯ ಸಾಮರ್ಥ್ಯ',
    earlyWarnings: 'ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು',
    simulationCard: 'ಹೀಗಾದರೆ? ಸಿಮ್ಯುಲೇಶನ್',
    currentSituation: 'ಪ್ರಸ್ತುತ ಪರಿಸ್ಥಿತಿ',
    activeAlerts: 'ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು',
    critical: 'ಗಂಭೀರ',
    sheltersReady: 'ಸಿದ್ಧ ಆಶ್ರಯಗಳು',
    operational: 'ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ',
    bedOccupancy: 'ಹಾಸಿಗೆ ಬಳಕೆ',
    operationalDesk: 'ಆಪರೇಷನಲ್ ಡೆಸ್ಕ್',
    populationAtRisk: 'ಅಪಾಯದಲ್ಲಿರುವ ಜನಸಂಖ್ಯೆ',
    threatLevel: 'ಬೆದರಿಕೆ ಮಟ್ಟ',
    activeSectors: 'ಸಕ್ರಿಯ ವಲಯಗಳು',
    riskDistribution: 'ಅಪಾಯ ವಿತರಣೆ',
    totalZones: 'ಒಟ್ಟು ವಲಯಗಳು',
    lowRisk: 'ಕಡಿಮೆ ಅಪಾಯ',
    mediumRisk: 'ಮಧ್ಯಮ ಅಪಾಯ',
    highRisk: 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
    viewFullRiskAnalysis: 'ಪೂರ್ಣ ವಿಶ್ಲೇಷಣೆ ವೀಕ್ಷಿಸಿ',
    riskScoreTrend: '24-ಗಂಟೆಯ ಅಪಾಯ ಸ್ಕೋರ್ ಪ್ರವೃತ್ತಿ',
    detailedTrendAnalysis: 'ವಿವರವಾದ ಪ್ರವೃತ್ತಿ ವಿಶ್ಲೇಷಣೆ',
    recentAlerts: 'ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    aiAssistant: 'ಎಐ ಸಹಾಯಕ'
  },
  ml: {
    appTitle: 'ആപദനേത്ര ദുരന്ത നിവാരണ പിന്തുണ',
    appSubtitle: 'തത്സമയ ഭൗമ വിവരങ്ങൾ • എഐ പ്രവചനങ്ങൾ • അടിയന്തര മാർഗ്ഗനിർദ്ദേശം',
    home: 'ഹോം',
    about: 'ഞങ്ങളെക്കുറിച്ച്',
    howItWorks: 'പ്രവർത്തനരീതി',
    contact: 'ബന്ധപ്പെടുക',
    changeLocation: 'സ്ഥലം മാറ്റുക',
    useGps: 'എന്റെ ലൈവ് ജിപിഎസ് ഉപയോഗിക്കുക',
    gpsActive: 'ജിപിഎസ് സജീവം',
    searchDistrict: 'ജില്ല തിരയുക (ഉദാ. കൊച്ചി, കോഴിക്കോട്)...',
    locationTelemetry: 'ലൊക്കേഷൻ ടെലിമെട്രി',
    notifications: 'അറിയിപ്പുകൾ',
    signOut: 'ലോഗ് ഔട്ട്',
    citizen: 'പൗരൻ',
    admin: 'അഡ്മിൻ',
    welcomeBack: 'സ്വാഗതം',
    signInPrompt: 'തുടരാൻ സൈൻ ഇൻ ചെയ്യുക',
    adminAccess: 'സുരക്ഷിത അഡ്മിൻ ആക്സസ്',
    mobileNumber: 'മൊബൈൽ നമ്പർ',
    enterMobile: '10 അക്ക മൊബൈൽ നമ്പർ നൽകുക',
    mobileHelper: 'രജിസ്റ്റർ ചെയ്ത മൊബൈൽ നമ്പർ.',
    emailAddress: 'ഇമെയിൽ വിലാസം',
    citizenEmail: 'പൗരന്റെ ഇമെയിൽ',
    citizenEmailHelper: 'രജിസ്റ്റർ ചെയ്ത പൗര ഇമെയിൽ.',
    adminId: 'അഡ്മിൻ ഐഡി',
    adminIdHelper: "ഫോർമാറ്റ്: 'NETRA' + 7 അക്കങ്ങൾ",
    password: 'പാസ്‌വേഡ്',
    enterPassword: 'പാസ്‌വേഡ് നൽകുക',
    rememberMe: 'എന്നെ ഓർക്കുക',
    forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
    forgotAdminPassword: 'അഡ്മിൻ പാസ്‌വേഡ് മറന്നോ?',
    signInWithMobile: 'മൊബൈൽ ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക',
    signInWithEmail: 'ഇമെയിൽ ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക',
    signInAsAdmin: 'അഡ്മിനായി സൈൻ ഇൻ ചെയ്യുക',
    authenticating: 'പരിശോധിക്കുന്നു...',
    or: 'അഥവാ',
    signInGoogle: 'Google വഴി സൈൻ ഇൻ ചെയ്യുക',
    dontHaveAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    createAccount: 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    saferPeople: 'സുരക്ഷിത ജനങ്ങൾ | കരുത്തുറ്റ സമൂഹം',
    platformSubtitle: 'പൊതു സുരക്ഷയും അടിയന്തര തീരുമാന സഹായ പ്ലാറ്റ്‌ഫോമും',
    publicSafety: 'പൊതു സുരക്ഷയും അടിയന്തര',
    decisionPlatform: 'തീരുമാന സഹായ പ്ലാറ്റ്‌ഫോം',
    missionStatement: 'സുരക്ഷിതമായ ഇന്ത്യക്കായി മികച്ച ദുരന്ത നിവാരണം.',
    anticipateRisks: 'അപകടങ്ങൾ മുൻകൂട്ടി അറിയുക',
    anticipateHelper: 'ഡാറ്റാധിഷ്ഠിത വിവരങ്ങൾ',
    enableResponse: 'വേഗത്തിലുള്ള പ്രതികരണം',
    responseHelper: 'ഏകോപിത പ്രവർത്തനം',
    buildCommunities: 'സുരക്ഷിത സമൂഹം പണിയുക',
    communitiesHelper: 'സുരക്ഷിതമായ നാളേക്ക്',
    together: 'ഒരുമിച്ച്',
    forASafer: 'സുരക്ഷിതമായ',
    tomorrow: 'നാളേക്ക്',
    togetherSafer: 'സുരക്ഷിതമായ നാളേക്ക് ഒന്നിച്ച്',
    disasterIntelligence: 'ദുരന്ത ഇന്റലിജൻസ്',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    footerResilient: 'സുരക്ഷിതവും സുദൃഢവുമായ ഒരു നാളെ പണിയുന്നു.',
    footerEmpowering: 'കൃത്യമായ വിവരങ്ങളിലൂടെ സമൂഹങ്ങളെ ശാക്തീകരിക്കുന്നു.',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    termsOfService: 'സേവന വ്യവസ്ഥകൾ',
    allRightsReserved: '© 2026. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.',

    // Sidebar
    aiDisasterIntelligence: 'എഐ ദുരന്ത ഇന്റലിജൻസ്',
    cmdIntelligence: 'കമാൻഡ് & ഇന്റലിജൻസ്',
    commandDashboard: 'കമാൻഡ് ഡാഷ്‌ബോർഡ്',
    liveDisasterMap: 'ലൈവ് ദുരന്ത ഭൂപടം',
    aiEmergencyAssistant: 'എഐ അടിയന്തര സഹായി',
    analyticsPredictions: 'വിശകലനങ്ങളും പ്രവചനങ്ങളും',
    citizenReports: 'പൗര റിപ്പോർട്ടുകൾ',
    temporalForecasts: 'സമയാധിഷ്ഠിത പ്രവചനങ്ങൾ',
    riskAnalysis: 'അപകടസാധ്യത വിശകലനം (XAI)',
    whatIfSimulation: '"എന്തെങ്കിലുമുണ്ടായാൽ?" സിമുലേഷൻ',
    operationsRelocation: 'പ്രവർത്തനങ്ങളും പുനരധിവാസവും',
    vulnerableHabitations: 'ദുർബല പ്രദേശങ്ങൾ',
    shelterCapacity: 'ദുരിതാശ്വാസ ക്യാമ്പ് ശേഷി',
    relocationPlans: 'പുനരധിവാസ പദ്ധതികൾ',
    userManagement: 'ഉപയോക്തൃ മാനേജ്‌മെന്റ്',
    system: 'സിസ്റ്റം',
    systemReports: 'സിസ്റ്റം റിപ്പോർട്ടുകൾ',
    settings: 'ക്രമീകരണങ്ങൾ',

    // Dashboard
    crisisDecisionCockpit: 'ദുരന്ത നിവാരണ കോക്ക്പിറ്റ്',
    welcomeBackUser: 'സ്വാഗതം',
    monitoring: 'നിരീക്ഷണം',
    live: 'ലൈവ്',
    liveMap: 'ലൈവ് മാപ്പ്',
    quickActions: 'ദ്രുത നടപടികൾ',
    citizenReportsCard: 'പൗര റിപ്പോർട്ടുകൾ',
    emergencyContacts: 'അടിയന്തര നമ്പറുകൾ',
    shelterCapacityCard: 'ക്യാമ്പ് ശേഷി',
    earlyWarnings: 'മുൻകൂർ മുന്നറിയിപ്പുകൾ',
    simulationCard: 'എന്തുണ്ടായാൽ? സിമുലേഷൻ',
    currentSituation: 'നിലവിലെ അവസ്ഥ',
    activeAlerts: 'സജീവ ജാഗ്രതാനിർദ്ദേശങ്ങൾ',
    critical: 'ഗുരുതരം',
    sheltersReady: 'തയ്യാറായ ക്യാമ്പുകൾ',
    operational: 'പ്രവർത്തനസജ്ജം',
    bedOccupancy: 'കിടക്ക ഉപയോഗം',
    operationalDesk: 'ഓപ്പറേഷൻസ് ഡെസ്ക്',
    populationAtRisk: 'അപകടത്തിലുള്ള ജനസംഖ്യ',
    threatLevel: 'ഭീഷണി നില',
    activeSectors: 'സജീവ മേഖലകൾ',
    riskDistribution: 'അപകടസാധ്യതാ വിതരണം',
    totalZones: 'ആകെ മേഖലകൾ',
    lowRisk: 'കുറഞ്ഞ സാധ്യത',
    mediumRisk: 'ഇടത്തരം സാധ്യത',
    highRisk: 'കൂടിയ സാധ്യത',
    viewFullRiskAnalysis: 'പൂർണ്ണ വിശകലനം കാണുക',
    riskScoreTrend: '24-മണിക്കൂർ റിസ്ക് സ്കോർ ട്രെൻഡ്',
    detailedTrendAnalysis: 'വിശദമായ ട്രെൻഡ് വിശകലനം',
    recentAlerts: 'സമീപകാല മുന്നറിയിപ്പുകൾ',
    viewAll: 'എല്ലാം കാണുക',
    aiAssistant: 'എഐ അസിസ്റ്റന്റ്'
  },
  pa: {
    appTitle: 'ਆਪਦਾਨੇਤਰ ਆਫ਼ਤ ਫੈਸਲਾ ਸਹਾਇਤਾ',
    appSubtitle: 'ਰੀਅਲ-ਟਾਈਮ ਭੂਗੋਲਿਕ ਇੰਟੈਲੀਜੈਂਸ • ਏਆਈ ਭਵਿੱਖਬਾਣੀ • ਸੰਕਟਕਾਲੀਨ ਮਾਰਗਦਰਸ਼ਨ',
    home: 'ਹੋਮ',
    about: 'ਸਾਡੇ ਬਾਰੇ',
    howItWorks: 'ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    contact: 'ਸੰਪਰਕ',
    changeLocation: 'ਸਥਾਨ ਬਦਲੋ',
    useGps: 'ਮੇਰਾ ਲਾਈਵ ਜੀਪੀਐਸ ਵਰਤੋ',
    gpsActive: 'ਜੀਪੀਐਸ ਕਿਰਿਆਸ਼ੀਲ',
    searchDistrict: 'ਜ਼ਿਲ੍ਹਾ ਖੋਜੋ (ਜਿਵੇਂ ਚੰਡੀਗੜ੍ਹ, ਅੰਮ੍ਰਿਤਸਰ)...',
    locationTelemetry: 'ਸਥਾਨ ਟੈਲੀਮੈਟਰੀ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    signOut: 'ਲੌਗ ਆਉਟ',
    citizen: 'ਨਾਗਰਿਕ',
    admin: 'ਪ੍ਰਸ਼ਾਸਕ',
    welcomeBack: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    signInPrompt: 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
    adminAccess: 'ਸੁਰੱਖਿਅਤ ਪ੍ਰਸ਼ਾਸਕ ਪਹੁੰਚ',
    mobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    enterMobile: '10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    mobileHelper: 'ਰਜਿਸਟਰਡ ਭਾਰਤੀ ਮੋਬਾਈਲ ਨੰਬਰ।',
    emailAddress: 'ਈਮੇਲ ਪਤਾ',
    citizenEmail: 'ਨਾਗਰਿਕ ਈਮੇਲ ਪਤਾ',
    citizenEmailHelper: 'ਰਜਿਸਟਰਡ ਨਾਗਰਿਕ ਈਮੇਲ।',
    adminId: 'ਐਡਮਿਨ ਆਈਡੀ',
    adminIdHelper: "ਫਾਰਮੈਟ: 'NETRA' + 7 ਅੰਕ",
    password: 'ਪਾਸਵਰਡ',
    enterPassword: 'ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
    rememberMe: 'ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ',
    forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    forgotAdminPassword: 'ਐਡਮਿਨ ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    signInWithMobile: 'ਮੋਬਾਈਲ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    signInWithEmail: 'ਈਮੇਲ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    signInAsAdmin: 'ਪ੍ਰਸ਼ਾਸਕ ਵਜੋਂ ਸਾਈਨ ਇਨ ਕਰੋ',
    authenticating: 'ਪ੍ਰਮਾਣਿਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    or: 'ਜਾਂ',
    signInGoogle: 'Google ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    dontHaveAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    saferPeople: 'ਸੁਰੱਖਿਅਤ ਲੋਕ | ਮਜ਼ਬੂਤ ਸਮਾਜ',
    platformSubtitle: 'ਜਨਤਕ ਸੁਰੱਖਿਆ ਅਤੇ ਸੰਕਟਕਾਲੀਨ ਫੈਸਲਾ ਸਹਾਇਤਾ ਮੰਚ',
    publicSafety: 'ਜਨਤਕ ਸੁਰੱਖਿਆ ਅਤੇ ਸੰਕਟਕਾਲੀਨ',
    decisionPlatform: 'ਫੈਸਲਾ ਸਹਾਇਤਾ ਮੰਚ',
    missionStatement: 'ਸੁਰੱਖਿਅਤ ਭਾਰਤ ਲਈ ਆਫ਼ਤ ਜੋਖਮ ਪ੍ਰਬੰਧਨ।',
    anticipateRisks: 'ਜੋਖਮਾਂ ਦਾ ਅੰਦਾਜ਼ਾ ਲਗਾਓ',
    anticipateHelper: 'ਡਾਟਾ-ਅਧਾਰਤ ਜਾਣਕਾਰੀ',
    enableResponse: 'ਤੇਜ਼ ਕਾਰਵਾਈ',
    responseHelper: 'ਤਾਲਮੇਲ ਵਾਲੀ ਕਾਰਵਾਈ',
    buildCommunities: 'ਸੁਰੱਖਿਅਤ ਸਮਾਜ ਬਣਾਓ',
    communitiesHelper: 'ਸੁਰੱਖਿਅਤ ਭਵਿੱਖ ਲਈ',
    together: 'ਇਕੱਠੇ',
    forASafer: 'ਸੁਰੱਖਿਅਤ ਭਲਕ',
    tomorrow: 'ਲਈ',
    togetherSafer: 'ਸੁਰੱਖਿਅਤ ਭਵਿੱਖ ਲਈ ਇਕੱਠੇ',
    disasterIntelligence: 'ਆਫ਼ਤ ਇੰਟੈਲੀਜੈਂਸ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    footerResilient: 'ਇੱਕ ਸੁਰੱਖਿਅਤ ਅਤੇ ਮਜ਼ਬੂਤ ਕੱਲ੍ਹ ਦਾ ਨਿਰਮਾਣ।',
    footerEmpowering: 'ਸਮੇਂ ਸਿਰ ਕਾਰਵਾਈ ਨਾਲ ਭਾਈਚਾਰਿਆਂ ਨੂੰ ਸਮਰੱਥ ਬਣਾਉਣਾ।',
    privacyPolicy: 'ਪਰਦੇਦਾਰੀ ਨੀਤੀ',
    termsOfService: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
    allRightsReserved: '© 2026. ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।',

    // Sidebar
    aiDisasterIntelligence: 'ਏਆਈ ਆਫ਼ਤ ਇੰਟੈਲੀਜੈਂਸ',
    cmdIntelligence: 'ਕਮਾਂਡ ਅਤੇ ਇੰਟੈਲੀਜੈਂਸ',
    commandDashboard: 'ਕਮਾਂਡ ਡੈਸ਼ਬੋਰਡ',
    liveDisasterMap: 'ਲਾਈਵ ਆਫ਼ਤ ਨਕਸ਼ਾ',
    aiEmergencyAssistant: 'ਏਆਈ ਐਮਰਜੈਂਸੀ ਸਹਾਇਕ',
    analyticsPredictions: 'ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਭਵਿੱਖਬਾਣੀਆਂ',
    citizenReports: 'ਨਾਗਰਿਕ ਰਿਪੋਰਟਾਂ',
    temporalForecasts: 'ਸਮੇਂ ਅਨੁਸਾਰ ਪੂਰਵ ਅਨੁਮਾਨ',
    riskAnalysis: 'ਜੋਖਮ ਵਿਸ਼ਲੇਸ਼ਣ (XAI)',
    whatIfSimulation: '"ਕੀ ਹੋਵੇਗਾ ਜੇ?" ਸਿਮੂਲੇਸ਼ਨ',
    operationsRelocation: 'ਓਪਰੇਸ਼ਨ ਅਤੇ ਪੁਨਰਵਾਸ',
    vulnerableHabitations: 'ਸੰਵੇਦਨਸ਼ੀਲ ਆਬਾਦੀਆਂ',
    shelterCapacity: 'ਸ਼ੈਲਟਰ ਸਮਰੱਥਾ',
    relocationPlans: 'ਪੁਨਰਵਾਸ ਯੋਜਨਾਵਾਂ',
    userManagement: 'ਯੂਜ਼ਰ ਪ੍ਰਬੰਧਨ',
    system: 'ਸਿਸਟਮ',
    systemReports: 'ਸਿਸਟਮ ਰਿਪੋਰਟਾਂ',
    settings: 'ਸੈਟਿੰਗਾਂ',

    // Dashboard
    crisisDecisionCockpit: 'ਸੰਕਟ ਫੈਸਲਾ ਕਾਕਪਿਟ',
    welcomeBackUser: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    monitoring: 'ਨਿਗਰਾਨੀ',
    live: 'ਲਾਈਵ',
    liveMap: 'ਲਾਈਵ ਨਕਸ਼ਾ',
    quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
    citizenReportsCard: 'ਨਾਗਰਿਕ ਰਿਪੋਰਟਾਂ',
    emergencyContacts: 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
    shelterCapacityCard: 'ਸ਼ੈਲਟਰ ਸਮਰੱਥਾ',
    earlyWarnings: 'ਅਗਾਊਂ ਚੇਤਾਵਨੀਆਂ',
    simulationCard: 'ਕੀ ਹੋਵੇਗਾ ਜੇ? ਸਿਮੂਲੇਸ਼ਨ',
    currentSituation: 'ਮੌਜੂਦਾ ਸਥਿਤੀ',
    activeAlerts: 'ਸਰਗਰਮ ਚੇਤਾਵਨੀਆਂ',
    critical: 'ਨਾਜ਼ੁਕ',
    sheltersReady: 'ਤਿਆਰ ਸ਼ੈਲਟਰ',
    operational: 'ਕਾਰਜਸ਼ੀਲ',
    bedOccupancy: 'ਬੈੱਡ ਵਰਤੋਂ',
    operationalDesk: 'ਓਪਰੇਸ਼ਨਲ ਡੈਸਕ',
    populationAtRisk: 'ਜੋਖਮ ਅਧੀਨ ਆਬਾਦੀ',
    threatLevel: 'ਖ਼ਤਰਾ ਪੱਧਰ',
    activeSectors: 'ਸਰਗਰਮ ਖੇਤਰ',
    riskDistribution: 'ਜੋਖਮ ਵੰਡ',
    totalZones: 'ਕੁੱਲ ਜ਼ੋਨ',
    lowRisk: 'ਘੱਟ ਜੋਖਮ',
    mediumRisk: 'ਦਰਮਿਆਨਾ ਜੋਖਮ',
    highRisk: 'ਉੱਚ ਜੋਖਮ',
    viewFullRiskAnalysis: 'ਪੂਰਾ ਵਿਸ਼ਲੇਸ਼ਣ ਦੇਖੋ',
    riskScoreTrend: '24-ਘੰਟੇ ਦਾ ਜੋਖਮ ਸਕੋਰ ਰੁਝਾਨ',
    detailedTrendAnalysis: 'ਵਿਸਤ੍ਰਿਤ ਰੁਝਾਨ ਵਿਸ਼ਲੇਸ਼ਣ',
    recentAlerts: 'ਹਾਲੀਆ ਚੇਤਾਵਨੀਆਂ',
    viewAll: 'ਸਾਰੇ ਦੇਖੋ',
    aiAssistant: 'ਏਆਈ ਸਹਾਇਕ'
  },
  or: {
    appTitle: 'ଆପଦାନେତ୍ର ବିପର୍ଯ୍ୟୟ ନିଷ୍ପତ୍ତି ସହାୟତା',
    appSubtitle: 'ରିଅଲ-ଟାଇମ୍ ଭୌଗୋଳିକ ସୂଚନା • ଏଆଇ ପୂର୍ବାନୁମାନ • ଜରୁରୀକାଳୀନ ମାର୍ଗଦର୍ଶନ',
    home: 'ମୂଳପୃଷ୍ଠା',
    about: 'ଆମ ବିଷୟରେ',
    howItWorks: 'କିପରି କାର୍ଯ୍ୟ କରେ',
    contact: 'ଯୋଗାଯୋଗ',
    changeLocation: 'ସ୍ଥାନ ପରିବର୍ତ୍ତନ',
    useGps: 'ମୋର ଲାଇଭ୍ ଜିପିଏସ୍ ବ୍ୟବହାର କରନ୍ତୁ',
    gpsActive: 'ଜିପିଏସ୍ ସକ୍ରିୟ',
    searchDistrict: 'ଜିଲ୍ଲା ଖୋଜନ୍ତୁ (ଯଥା ଭୁବନେଶ୍ୱର, କଟକ)...',
    locationTelemetry: 'ସ୍ଥାନ ଟେଲିମେଟ୍ରି',
    notifications: 'ବିଜ୍ଞପ୍ତି',
    signOut: 'ଲଗ୍ ଆଉଟ୍',
    citizen: 'ନାଗରିକ',
    admin: 'ପ୍ରଶାସକ',
    welcomeBack: 'ସ୍ୱାଗତ',
    signInPrompt: 'ଜାରି ରଖିବାକୁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    adminAccess: 'ସୁରକ୍ଷିତ ପ୍ରଶାସକ ପ୍ରବେଶ',
    mobileNumber: 'ମୋବାଇଲ୍ ନମ୍ବର',
    enterMobile: '୧୦ ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ',
    mobileHelper: 'ପଞ୍ଜୀକୃତ ଭାରତୀୟ ମୋବାଇଲ୍ ନମ୍ବର।',
    emailAddress: 'ଇମେଲ୍ ଠିକଣା',
    citizenEmail: 'ନାଗରିକ ଇମେଲ୍ ଠିକଣା',
    citizenEmailHelper: 'ପଞ୍ଜୀକୃତ ନାଗରିକ ଇମେଲ୍।',
    adminId: 'ଆଡମିନ୍ ଆଇଡି',
    adminIdHelper: "ଫର୍ମାଟ୍: 'NETRA' + ୭ ଅଙ୍କ",
    password: 'ପାସୱାର୍ଡ',
    enterPassword: 'ପାସୱାର୍ଡ ଦିଅନ୍ତୁ',
    rememberMe: 'ମନେ ରଖନ୍ତୁ',
    forgotPassword: 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ?',
    forgotAdminPassword: 'ଆଡମିନ୍ ପାସୱାର୍ଡ ଭୁଲିଗଲେ?',
    signInWithMobile: 'ମୋବାଇଲ୍ ସହିତ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    signInWithEmail: 'ଇମେଲ୍ ସହିତ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    signInAsAdmin: 'ପ୍ରଶାସକ ଭାବରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    authenticating: 'ଯାଞ୍ଚ ହେଉଛି...',
    or: 'କିମ୍ବା',
    signInGoogle: 'Google ସହିତ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    dontHaveAccount: 'ଖାତା ନାହିଁ କି?',
    createAccount: 'ଖାତା ଖୋଲନ୍ତୁ',
    saferPeople: 'ସୁରକ୍ଷିତ ଲୋକ | ଶକ୍ତିଶାଳୀ ସମାଜ',
    platformSubtitle: 'ଜନସାଧାରଣ ସୁରକ୍ଷା ଓ ଜରୁରୀକାଳୀନ ନିଷ୍ପତ୍ତି ସହାୟତା ପ୍ଲାଟଫର୍ମ',
    publicSafety: 'ଜନସାଧାରଣ ସୁରକ୍ଷା ଓ ଜରୁରୀକାଳୀନ',
    decisionPlatform: 'ନିଷ୍ପତ୍ତି ସହାୟତା ପ୍ଲାଟଫର୍ମ',
    missionStatement: 'ସୁରକ୍ଷିତ ଭାରତ ପାଇଁ ବିପର୍ଯ୍ୟୟ ବିପଦ ପରିଚାଳନା।',
    anticipateRisks: 'ବିପଦର ଆଗୁଆ ଅନୁମାନ',
    anticipateHelper: 'ତଥ୍ୟ-ଆଧାରିତ ସୂଚନା',
    enableResponse: 'ଦ୍ରୁତ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ',
    responseHelper: 'ସମନ୍ୱିତ ପଦକ୍ଷେପ',
    buildCommunities: 'ସୁରକ୍ଷିତ ସମାଜ ନିର୍ମାଣ',
    communitiesHelper: 'ଉନ୍ନତ ଭବିଷ୍ୟତ ପାଇଁ',
    together: 'ଏକତ୍ର',
    forASafer: 'ସୁରକ୍ଷିତ ଆଗାମୀ',
    tomorrow: 'କାଲି ପାଇଁ',
    togetherSafer: 'ସୁରକ୍ଷିତ ଆଗାମୀ କାଲି ପାଇଁ ଏକତ୍ର',
    disasterIntelligence: 'ବିପର୍ଯ୍ୟୟ ଇଣ୍ଟେଲିଜେନ୍ସ',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    footerResilient: 'ସୁରକ୍ଷିତ ଏବଂ ଶକ୍ତିଶାଳୀ ଆଗାମୀ କାଲି ନିର୍ମାଣ।',
    footerEmpowering: 'ସଠିକ୍ ତଥ୍ୟ ଦ୍ୱାରା ସମାଜର ସଶକ୍ତୀକରଣ।',
    privacyPolicy: 'ଗୋପନୀୟତା ନୀତି',
    termsOfService: 'ସେବା ସର୍ତ୍ତାବଳୀ',
    allRightsReserved: '© ୨୦୨୬. ସର୍ବସ୍ୱତ୍ୱ ସଂରକ୍ଷିତ।',

    // Sidebar
    aiDisasterIntelligence: 'ଏଆଇ ବିପର୍ଯ୍ୟୟ ଇଣ୍ଟେଲିଜେନ୍ସ',
    cmdIntelligence: 'କମାଣ୍ଡ ଏବଂ ଇଣ୍ଟେଲିଜେନ୍ସ',
    commandDashboard: 'କମାଣ୍ଡ ଡ୍ୟାସବୋର୍ଡ',
    liveDisasterMap: 'ଲାଇଭ୍ ବିପର୍ଯ୍ୟୟ ମାନଚିତ୍ର',
    aiEmergencyAssistant: 'ଏଆଇ ଜରୁରୀକାଳୀନ ସହାୟକ',
    analyticsPredictions: 'ବିଶ୍ଳେଷଣ ଏବଂ ପୂର୍ବାନୁମାନ',
    citizenReports: 'ନାଗରିକ ରିପୋର୍ଟ',
    temporalForecasts: 'ସମୟାନୁସାରୀ ପୂର୍ବାନୁମାନ',
    riskAnalysis: 'ବିପଦ ବିଶ୍ଳେଷଣ (XAI)',
    whatIfSimulation: '"ଯଦି ଏପରି ହୁଏ?" ସିମ୍ୟୁଲେସନ୍',
    operationsRelocation: 'ଅପରେସନ୍ସ ଏବଂ ପୁନର୍ବାସ',
    vulnerableHabitations: 'ସମ୍ବେଦନଶୀଳ ବସତି',
    shelterCapacity: 'ଆଶ୍ରୟସ୍ଥଳୀ କ୍ଷମତା',
    relocationPlans: 'ପୁନର୍ବାସ ଯୋଜନା',
    userManagement: 'ଉପଭୋକ୍ତା ପରିଚାଳନା',
    system: 'ସିଷ୍ଟମ୍',
    systemReports: 'ସିଷ୍ଟମ୍ ରିପୋର୍ଟ',
    settings: 'ସେଟିଙ୍ଗ୍ସ',

    // Dashboard
    crisisDecisionCockpit: 'ବିପର୍ଯ୍ୟୟ ନିଷ୍ପତ୍ତି କକ୍‌ପିଟ୍',
    welcomeBackUser: 'ସ୍ୱାଗତ',
    monitoring: 'ନିରୀକ୍ଷଣ',
    live: 'ଲାଇଭ୍',
    liveMap: 'ଲାଇଭ୍ ମାନଚିତ୍ର',
    quickActions: 'ଦ୍ରୁତ ପଦକ୍ଷେପ',
    citizenReportsCard: 'ନାଗରିକ ରିପୋର୍ଟ',
    emergencyContacts: 'ଜରୁରୀକାଳୀନ ଯୋଗାଯୋଗ',
    shelterCapacityCard: 'ଆଶ୍ରୟସ୍ଥଳୀ କ୍ଷମତା',
    earlyWarnings: 'ପୂର୍ବ ସତର୍କତା',
    simulationCard: 'ଯଦି ଏପରି ହୁଏ? ସିମ୍ୟୁଲେସନ୍',
    currentSituation: 'ବର୍ତ୍ତମାନର ସ୍ଥିତି',
    activeAlerts: 'ସକ୍ରିୟ ଚେତାବନୀ',
    critical: 'ସଙ୍କଟଜନକ',
    sheltersReady: 'ପ୍ରସ୍ତୁତ ଆଶ୍ରୟସ୍ଥଳୀ',
    operational: 'କାର୍ଯ୍ୟକ୍ଷମ',
    bedOccupancy: 'ବେଡ୍ ବ୍ୟବହାର',
    operationalDesk: 'ଅପରେସନାଲ୍ ଡେସ୍କ',
    populationAtRisk: 'ବିପଦରେ ଥିବା ଜନସଂଖ୍ୟା',
    threatLevel: 'ବିପଦ ସ୍ତର',
    activeSectors: 'ସକ୍ରିୟ ସେକ୍ଟର',
    riskDistribution: 'ବିପଦ ବଣ୍ଟନ',
    totalZones: 'ମୋଟ ଜୋନ୍',
    lowRisk: 'କମ୍ ବିପଦ',
    mediumRisk: 'ମଧ୍ୟମ ବିପଦ',
    highRisk: 'ଉଚ୍ଚ ବିପଦ',
    viewFullRiskAnalysis: 'ସମ୍ପୂର୍ଣ୍ଣ ବିଶ୍ଳେଷଣ ଦେଖନ୍ତୁ',
    riskScoreTrend: '୨୪-ଘଣ୍ଟା ବିପଦ ସ୍କୋର ଧାରା',
    detailedTrendAnalysis: 'ବିସ୍ତୃତ ଧାରା ବିଶ୍ଳେଷଣ',
    recentAlerts: 'ସାମ୍ପ୍ରତିକ ଚେତାବନୀ',
    viewAll: 'ସବୁ ଦେଖନ୍ତୁ',
    aiAssistant: 'ଏଆଇ ସହାୟକ'
  },
  as: {
    appTitle: 'আপদানেত্ৰ সংকট সিদ্ধান্ত সাহায্য',
    appSubtitle: 'ৰিয়েল-টাইম ভূ-स्थानিক বুদ্ধিমত্তা • এআই পূৰ্বাভাস • জৰুৰীকালীন নিৰ্দেশনা',
    home: 'গৃহ',
    about: 'আমাৰ বিষয়ে',
    howItWorks: 'কাৰ্যপদ্ধতি',
    contact: 'যোগাযোগ',
    changeLocation: 'স্থান সলনি কৰক',
    useGps: 'মোৰ লাইভ জিপিএছ ব্যৱহাৰ কৰক',
    gpsActive: 'জিপিএছ সক্ৰিয়',
    searchDistrict: 'জিলা সন্ধান কৰক (যেনে গুৱাহাটী, শিলচৰ)...',
    locationTelemetry: 'স্থান টেলিমেট্ৰি',
    notifications: 'জাননী',
    signOut: 'লগ আউট',
    citizen: 'নাগৰিক',
    admin: 'প্ৰশাসক',
    welcomeBack: 'স্বাগতম',
    signInPrompt: 'আগবাঢ়িবলৈ ছাইন ইন কৰক',
    adminAccess: 'সুৰক্ষিত প্ৰশাসক প্ৰৱেশ',
    mobileNumber: 'মোবাইল নম্বৰ',
    enterMobile: '১০ টা সংখ্যাৰ মোবাইল নম্বৰ দিয়ক',
    mobileHelper: 'পঞ্জীভুক্ত ভাৰতীয় মোবাইল নম্বৰ।',
    emailAddress: 'ইমেইল ঠিকনা',
    citizenEmail: 'নাগৰিক ইমেইল ঠিকনা',
    citizenEmailHelper: 'পঞ্জীভুক্ত নাগৰিক ইমেইল।',
    adminId: 'এডমিন আইডি',
    adminIdHelper: "বিন্যাস: 'NETRA' + ৭ টা সংখ্যা",
    password: 'পাছৱৰ্ড',
    enterPassword: 'পাছৱৰ্ড দিয়ক',
    rememberMe: 'মনত ৰাখক',
    forgotPassword: 'পাছৱৰ্ড পাহৰিলে?',
    forgotAdminPassword: 'এডমিন পাছৱৰ্ড পাহৰিলে?',
    signInWithMobile: 'মোবাইলেৰে ছাইন ইন কৰক',
    signInWithEmail: 'ইমেইলেৰে ছাইন ইন কৰক',
    signInAsAdmin: 'প্ৰশাসক হিচাপে ছাইন ইন কৰক',
    authenticating: 'প্ৰমাণীকৰণ চলি আছে...',
    or: 'অথবা',
    signInGoogle: 'Google ৰে ছাইন ইন কৰক',
    dontHaveAccount: 'একাউণ্ট নাই?',
    createAccount: 'একাউণ্ট সৃষ্টি কৰক',
    saferPeople: 'সুৰক্ষিত মানুহ | শক্তিশালী সমাজ',
    platformSubtitle: 'ৰাজহুৱা সুৰক্ষা আৰু জৰুৰীকালীন সিদ্ধান্ত সমৰ্থন মঞ্চ',
    publicSafety: 'ৰাজহুৱা সুৰক্ষা আৰু জৰুৰীকালীন',
    decisionPlatform: 'সিদ্ধান্ত সমৰ্থন মঞ্চ',
    missionStatement: 'সুৰক্ষিত আৰু শক্তিশালী ভাৰতৰ বাবে দুৰ্যোগ বিপদাশংকা ব্যৱস্থাপনা।',
    anticipateRisks: 'বিপদৰ আগলি বতৰা',
    anticipateHelper: 'তথ্য-আধাৰিত অন্তৰ্দৃষ্টি',
    enableResponse: 'দ্ৰুত সঁহাৰি',
    responseHelper: 'সমন্বিত পদক্ষেপ',
    buildCommunities: 'সুৰক্ষিত সমাজ গঠন',
    communitiesHelper: 'উজ্জ্বল ভৱিষ্যতৰ বাবে',
    together: 'একেলগে',
    forASafer: 'সুৰক্ষিত কাইলৈৰ',
    tomorrow: 'বাবে',
    togetherSafer: 'সুৰক্ষিত কাইলৈৰ বাবে একেলগে',
    disasterIntelligence: 'দুৰ্যোগ বুদ্ধিমত্তা',
    selectLanguage: 'ভাষা বাছক',
    footerResilient: 'এক সুৰক্ষিত আৰু শক্তিশালী ভৱিষ্যত গঠন।',
    footerEmpowering: 'সঠিক তথ্যৰে সম্প্ৰদায়সমূহক শক্তিশালী কৰা।',
    privacyPolicy: 'গোপনীয়তা নীতি',
    termsOfService: 'সেৱাৰ চৰ্তসমূহ',
    allRightsReserved: '© ২০২৬. সৰ্বস্বত্ব সংৰক্ষিত।',

    // Sidebar
    aiDisasterIntelligence: 'এআই দুৰ্যোগ বুদ্ধিমত্তা',
    cmdIntelligence: 'কমাণ্ড আৰু বুদ্ধিমত্তা',
    commandDashboard: 'কমাণ্ড ডেচবৰ্ড',
    liveDisasterMap: 'লাইভ দুৰ্যোগ মানচিত্ৰ',
    aiEmergencyAssistant: 'এআই জৰুৰীকালীন সহায়ক',
    analyticsPredictions: 'বিশ্লেষণ আৰু পূৰ্বাভাস',
    citizenReports: 'নাগৰিক প্ৰতিবেদন',
    temporalForecasts: 'সময়ভিত্তিক পূৰ্বাভাস',
    riskAnalysis: 'বিপদ বিশ্লেষণ (XAI)',
    whatIfSimulation: '"যদি এনে হয়?" অনুকৰণ',
    operationsRelocation: 'কাৰ্যকলাপ আৰু পুনৰ্সংস্থাপন',
    vulnerableHabitations: 'সংবেদনশীল বসতি',
    shelterCapacity: 'আশ্ৰয় শিবিৰৰ ক্ষমতা',
    relocationPlans: 'পুনৰ্সংস্থাপন পৰিকল্পনা',
    userManagement: 'ব্যৱহাৰকাৰী ব্যৱস্থাপনা',
    system: 'ব্যৱস্থা',
    systemReports: 'ব্যৱস্থাৰ প্ৰতিবেদন',
    settings: 'ছেটিংছ',

    // Dashboard
    crisisDecisionCockpit: 'সংকট সিদ্ধান্ত ককপিট',
    welcomeBackUser: 'স্বাগতম',
    monitoring: 'নিৰীক্ষণ',
    live: 'লাইভ',
    liveMap: 'লাইভ মানচিত্ৰ',
    quickActions: 'দ্ৰুত পদক্ষেপ',
    citizenReportsCard: 'নাগৰিক প্ৰতিবেদন',
    emergencyContacts: 'জৰুৰীকালীন যোগাযোগ',
    shelterCapacityCard: 'আশ্ৰয় ক্ষমতা',
    earlyWarnings: 'আগতীয়া সতৰ্কবাণী',
    simulationCard: 'কি হ’ব যদি? অনুকৰণ',
    currentSituation: 'বৰ্তমান পৰিস্থিতি',
    activeAlerts: 'সক্ৰিয় সতৰ্কবাণী',
    critical: 'সংকটজনক',
    sheltersReady: 'প্ৰস্তুত শিবিৰ',
    operational: 'কাৰ্যক্ষম',
    bedOccupancy: 'বিচনা দখল',
    operationalDesk: 'অপাৰেশ্যনেল ডেস্ক',
    populationAtRisk: 'বিপদত থকা জনসংখ্যা',
    threatLevel: 'ভাবুকিৰ মাত্ৰা',
    activeSectors: 'সক্ৰিয় খণ্ড',
    riskDistribution: 'বিপদ বিতৰণ',
    totalZones: 'মুঠ মণ্ডল',
    lowRisk: 'নিম্ন বিপদ',
    mediumRisk: 'মধ্যম বিপদ',
    highRisk: 'উচ্চ বিপদ',
    viewFullRiskAnalysis: 'সম্পূৰ্ণ বিশ্লেষণ চাওক',
    riskScoreTrend: '২৪-ঘণ্টাৰ বিপদ স্ক’ৰ গতিধাৰা',
    detailedTrendAnalysis: 'বিতং গতিধাৰা বিশ্লেষণ',
    recentAlerts: 'শেহতীয়া সতৰ্কবাণী',
    viewAll: 'সকলো চাওক',
    aiAssistant: 'এআই সহায়ক'
  }
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key, fallback) => fallback || key,
  languages: INDIAN_LANGUAGES
});

// Helper to trigger Google Translate in-page combo
function triggerGoogleCombo(langCode) {
  const domain = window.location.hostname;
  if (langCode === 'en') {
    document.cookie = 'googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';
    document.cookie = `googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; domain=${domain}; path=/;`;
  } else {
    document.cookie = `googtrans=/en/${langCode}; path=/;`;
    document.cookie = `googtrans=/en/${langCode}; domain=${domain}; path=/;`;
  }

  let attempts = 0;
  const interval = setInterval(() => {
    attempts++;
    const combo = document.querySelector('.goog-te-combo');
    if (combo) {
      combo.value = langCode;
      combo.dispatchEvent(new Event('change'));
      clearInterval(interval);
    }
    if (attempts > 30) {
      clearInterval(interval);
    }
  }, 100);
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('aapdanetra_language') || 'en';
    } catch {
      return 'en';
    }
  });

  // Initialize Google Translate background script once
  useEffect(() => {
    // 1. Invisible element container
    if (!document.getElementById('google_translate_element')) {
      const div = document.createElement('div');
      div.id = 'google_translate_element';
      div.style.cssText = 'position:absolute;top:-9999px;left:-9999px;width:1px;height:1px;overflow:hidden;opacity:0;pointer-events:none;';
      document.body.appendChild(div);
    }

    // 2. Global callback for Google Translate
    window.googleTranslateElementInit = () => {
      try {
        new window.google.translate.TranslateElement(
          {
            pageLanguage: 'en',
            includedLanguages: 'en,hi,bn,te,mr,ta,gu,kn,ml,pa,or,as',
            autoDisplay: false,
          },
          'google_translate_element'
        );
        const currentLang = localStorage.getItem('aapdanetra_language') || 'en';
        if (currentLang !== 'en') {
          setTimeout(() => triggerGoogleCombo(currentLang), 500);
        }
      } catch (e) {
        console.warn('Google Translate initialization:', e);
      }
    };

    // 3. Inject script
    if (!document.getElementById('google-translate-script')) {
      const script = document.createElement('script');
      script.id = 'google-translate-script';
      script.type = 'text/javascript';
      script.src = 'https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';
      script.async = true;
      document.body.appendChild(script);
    }

    // Sync cookie on load
    const saved = localStorage.getItem('aapdanetra_language') || 'en';
    if (saved !== 'en') {
      const domain = window.location.hostname;
      document.cookie = `googtrans=/en/${saved}; path=/;`;
      document.cookie = `googtrans=/en/${saved}; domain=${domain}; path=/;`;
    }
  }, []);

  const setLanguage = (langCode) => {
    setLanguageState(langCode);
    try {
      localStorage.setItem('aapdanetra_language', langCode);
      document.documentElement.lang = langCode;
      triggerGoogleCombo(langCode);
    } catch (e) {
      console.error(e);
    }
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key, fallback = '') => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict && langDict[key] !== undefined) {
      return langDict[key];
    }
    const defaultDict = TRANSLATIONS.en;
    if (defaultDict && defaultDict[key] !== undefined) {
      return defaultDict[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: INDIAN_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
